//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Clase Java para DeploymentDuration complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="DeploymentDuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="dug-in" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="entrenched" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="fortified" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeploymentDuration", propOrder = {
    "deployed",
    "dugIn",
    "entrenched",
    "fortified"
})
public class DeploymentDuration {

    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar deployed;
    @XmlElement(name = "dug-in", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dugIn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar entrenched;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar fortified;
    private final transient ObjectProperty<XMLGregorianCalendar> deployedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> dugInProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> entrenchedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> fortifiedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();

    /**
     * Define el valor de la propiedad deployed.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeployed(XMLGregorianCalendar value) {
        this.deployed = value;
        this.deployedProxy.set(value);
    }

    /**
     * Define el valor de la propiedad dugIn.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDugIn(XMLGregorianCalendar value) {
        this.dugIn = value;
        this.dugInProxy.set(value);
    }

    /**
     * Define el valor de la propiedad entrenched.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntrenched(XMLGregorianCalendar value) {
        this.entrenched = value;
        this.entrenchedProxy.set(value);
    }

    /**
     * Define el valor de la propiedad fortified.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFortified(XMLGregorianCalendar value) {
        this.fortified = value;
        this.fortifiedProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad deployed.
     * 
     */
    public XMLGregorianCalendar getDeployed() {
        if (this.deployedProxy.get() == null) {
            this.deployedProxy.set(deployed);
        }
        return this.deployedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> deployedProperty() {
        return this.deployedProxy;
    }

    /**
     * Obtiene el valor de la propiedad dugIn.
     * 
     */
    public XMLGregorianCalendar getDugIn() {
        if (this.dugInProxy.get() == null) {
            this.dugInProxy.set(dugIn);
        }
        return this.dugInProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> dugInProperty() {
        return this.dugInProxy;
    }

    /**
     * Obtiene el valor de la propiedad entrenched.
     * 
     */
    public XMLGregorianCalendar getEntrenched() {
        if (this.entrenchedProxy.get() == null) {
            this.entrenchedProxy.set(entrenched);
        }
        return this.entrenchedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> entrenchedProperty() {
        return this.entrenchedProxy;
    }

    /**
     * Obtiene el valor de la propiedad fortified.
     * 
     */
    public XMLGregorianCalendar getFortified() {
        if (this.fortifiedProxy.get() == null) {
            this.fortifiedProxy.set(fortified);
        }
        return this.fortifiedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> fortifiedProperty() {
        return this.fortifiedProxy;
    }

}
