//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para FormationSecurity complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="FormationSecurity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="front" type="{}Security"/>
 *         &lt;element name="left" type="{}Security"/>
 *         &lt;element name="right" type="{}Security"/>
 *         &lt;element name="rear" type="{}Security"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormationSecurity", propOrder = {
    "front",
    "left",
    "right",
    "rear"
})
public class FormationSecurity {

    @XmlElement(required = true)
    protected Security front;
    @XmlElement(required = true)
    protected Security left;
    @XmlElement(required = true)
    protected Security right;
    @XmlElement(required = true)
    protected Security rear;
    private final transient ObjectProperty<Security> frontProxy = new SimpleObjectProperty<Security>();
    private final transient ObjectProperty<Security> leftProxy = new SimpleObjectProperty<Security>();
    private final transient ObjectProperty<Security> rightProxy = new SimpleObjectProperty<Security>();
    private final transient ObjectProperty<Security> rearProxy = new SimpleObjectProperty<Security>();

    /**
     * Define el valor de la propiedad front.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setFront(Security value) {
        this.front = value;
        this.frontProxy.set(value);
    }

    /**
     * Define el valor de la propiedad left.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setLeft(Security value) {
        this.left = value;
        this.leftProxy.set(value);
    }

    /**
     * Define el valor de la propiedad right.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setRight(Security value) {
        this.right = value;
        this.rightProxy.set(value);
    }

    /**
     * Define el valor de la propiedad rear.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setRear(Security value) {
        this.rear = value;
        this.rearProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad front.
     * 
     */
    public Security getFront() {
        if (this.frontProxy.get() == null) {
            this.frontProxy.set(front);
        }
        return this.frontProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Security> frontProperty() {
        return this.frontProxy;
    }

    /**
     * Obtiene el valor de la propiedad left.
     * 
     */
    public Security getLeft() {
        if (this.leftProxy.get() == null) {
            this.leftProxy.set(left);
        }
        return this.leftProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Security> leftProperty() {
        return this.leftProxy;
    }

    /**
     * Obtiene el valor de la propiedad right.
     * 
     */
    public Security getRight() {
        if (this.rightProxy.get() == null) {
            this.rightProxy.set(right);
        }
        return this.rightProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Security> rightProperty() {
        return this.rightProxy;
    }

    /**
     * Obtiene el valor de la propiedad rear.
     * 
     */
    public Security getRear() {
        if (this.rearProxy.get() == null) {
            this.rearProxy.set(rear);
        }
        return this.rearProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Security> rearProperty() {
        return this.rearProxy;
    }

}
