//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para RadioSize complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="RadioSize">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="weight" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioSize")
public class RadioSize {

    @XmlAttribute(name = "width", required = true)
    protected float width;
    @XmlAttribute(name = "height", required = true)
    protected float height;
    @XmlAttribute(name = "length", required = true)
    protected float length;
    @XmlAttribute(name = "weight", required = true)
    protected float weight;
    private final transient FloatProperty widthProxy = new SimpleFloatProperty();
    private final transient FloatProperty heightProxy = new SimpleFloatProperty();
    private final transient FloatProperty lengthProxy = new SimpleFloatProperty();
    private final transient FloatProperty weightProxy = new SimpleFloatProperty();

    /**
     * Define el valor de la propiedad width.
     * 
     */
    public void setWidth(float value) {
        this.width = value;
        this.widthProxy.set(value);
    }

    /**
     * Define el valor de la propiedad height.
     * 
     */
    public void setHeight(float value) {
        this.height = value;
        this.heightProxy.set(value);
    }

    /**
     * Define el valor de la propiedad length.
     * 
     */
    public void setLength(float value) {
        this.length = value;
        this.lengthProxy.set(value);
    }

    /**
     * Define el valor de la propiedad weight.
     * 
     */
    public void setWeight(float value) {
        this.weight = value;
        this.weightProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad width.
     * 
     */
    public float getWidth() {
        return this.widthProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty widthProperty() {
        return this.widthProxy;
    }

    /**
     * Obtiene el valor de la propiedad height.
     * 
     */
    public float getHeight() {
        return this.heightProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty heightProperty() {
        return this.heightProxy;
    }

    /**
     * Obtiene el valor de la propiedad length.
     * 
     */
    public float getLength() {
        return this.lengthProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty lengthProperty() {
        return this.lengthProxy;
    }

    /**
     * Obtiene el valor de la propiedad weight.
     * 
     */
    public float getWeight() {
        return this.weightProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty weightProperty() {
        return this.weightProxy;
    }

}
