//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para RangeItem complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="RangeItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="range" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="accuracy" use="required" type="{}Proportion" />
 *       &lt;attribute name="armour-penetration" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RangeItem")
public class RangeItem {

    @XmlAttribute(name = "range", required = true)
    protected int range;
    @XmlAttribute(name = "accuracy", required = true)
    protected float accuracy;
    @XmlAttribute(name = "armour-penetration", required = true)
    protected float armourPenetration;
    private final transient IntegerProperty rangeProxy = new SimpleIntegerProperty();
    private final transient FloatProperty accuracyProxy = new SimpleFloatProperty();
    private final transient FloatProperty armourPenetrationProxy = new SimpleFloatProperty();

    /**
     * Define el valor de la propiedad range.
     * 
     */
    public void setRange(int value) {
        this.range = value;
        this.rangeProxy.set(value);
    }

    /**
     * Define el valor de la propiedad accuracy.
     * 
     */
    public void setAccuracy(float value) {
        this.accuracy = value;
        this.accuracyProxy.set(value);
    }

    /**
     * Define el valor de la propiedad armourPenetration.
     * 
     */
    public void setArmourPenetration(float value) {
        this.armourPenetration = value;
        this.armourPenetrationProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad range.
     * 
     */
    public int getRange() {
        return this.rangeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty rangeProperty() {
        return this.rangeProxy;
    }

    /**
     * Obtiene el valor de la propiedad accuracy.
     * 
     */
    public float getAccuracy() {
        return this.accuracyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty accuracyProperty() {
        return this.accuracyProxy;
    }

    /**
     * Obtiene el valor de la propiedad armourPenetration.
     * 
     */
    public float getArmourPenetration() {
        return this.armourPenetrationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty armourPenetrationProperty() {
        return this.armourPenetrationProxy;
    }

}
