//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para Rank complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="Rank">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="short-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="full-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rank")
public class Rank {

    @XmlAttribute(name = "short-name")
    protected String shortName;
    @XmlAttribute(name = "full-name")
    protected String fullName;
    private final transient StringProperty shortNameProxy = new SimpleStringProperty();
    private final transient StringProperty fullNameProxy = new SimpleStringProperty();

    /**
     * Define el valor de la propiedad shortName.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
        this.shortNameProxy.set(value);
    }

    /**
     * Define el valor de la propiedad fullName.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
        this.fullNameProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad shortName.
     * 
     */
    public String getShortName() {
        if (this.shortNameProxy.get() == null) {
            this.shortNameProxy.set(shortName);
        }
        return this.shortNameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty shortNameProperty() {
        return this.shortNameProxy;
    }

    /**
     * Obtiene el valor de la propiedad fullName.
     * 
     */
    public String getFullName() {
        if (this.fullNameProxy.get() == null) {
            this.fullNameProxy.set(fullName);
        }
        return this.fullNameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty fullNameProperty() {
        return this.fullNameProxy;
    }

}
