//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para RGBColor complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="RGBColor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RGBColor")
public class RGBColor {

    @XmlAttribute(name = "red")
    protected Integer red;
    @XmlAttribute(name = "green")
    protected Integer green;
    @XmlAttribute(name = "blue")
    protected Integer blue;
    private final transient IntegerProperty redProxy = new SimpleIntegerProperty();
    private final transient IntegerProperty greenProxy = new SimpleIntegerProperty();
    private final transient IntegerProperty blueProxy = new SimpleIntegerProperty();

    /**
     * Define el valor de la propiedad red.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRed(Integer value) {
        this.red = value;
        this.redProxy.set(value);
    }

    /**
     * Define el valor de la propiedad green.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGreen(Integer value) {
        this.green = value;
        this.greenProxy.set(value);
    }

    /**
     * Define el valor de la propiedad blue.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlue(Integer value) {
        this.blue = value;
        this.blueProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad red.
     * 
     */
    public Integer getRed() {
        return this.redProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty redProperty() {
        return this.redProxy;
    }

    /**
     * Obtiene el valor de la propiedad green.
     * 
     */
    public Integer getGreen() {
        return this.greenProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty greenProperty() {
        return this.greenProxy;
    }

    /**
     * Obtiene el valor de la propiedad blue.
     * 
     */
    public Integer getBlue() {
        return this.blueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty blueProperty() {
        return this.blueProxy;
    }

}
