//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para ROF complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="ROF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="slow" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="normal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="rapid" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ROF")
public class ROF {

    @XmlAttribute(name = "slow")
    protected Float slow;
    @XmlAttribute(name = "normal")
    protected Float normal;
    @XmlAttribute(name = "rapid")
    protected Float rapid;
    private final transient FloatProperty slowProxy = new SimpleFloatProperty();
    private final transient FloatProperty normalProxy = new SimpleFloatProperty();
    private final transient FloatProperty rapidProxy = new SimpleFloatProperty();

    /**
     * Define el valor de la propiedad slow.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSlow(Float value) {
        this.slow = value;
        this.slowProxy.set(value);
    }

    /**
     * Define el valor de la propiedad normal.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNormal(Float value) {
        this.normal = value;
        this.normalProxy.set(value);
    }

    /**
     * Define el valor de la propiedad rapid.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRapid(Float value) {
        this.rapid = value;
        this.rapidProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad slow.
     * 
     */
    public Float getSlow() {
        return this.slowProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty slowProperty() {
        return this.slowProxy;
    }

    /**
     * Obtiene el valor de la propiedad normal.
     * 
     */
    public Float getNormal() {
        return this.normalProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty normalProperty() {
        return this.normalProxy;
    }

    /**
     * Obtiene el valor de la propiedad rapid.
     * 
     */
    public Float getRapid() {
        return this.rapidProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rapidProperty() {
        return this.rapidProxy;
    }

}
