//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.7 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: 2014.10.26 a las 10:08:24 AM CET 
//


package net.deludobellico.stabeditor.model.temp;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para TargetPercentages complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType name="TargetPercentages">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="front" type="{}Proportion"/>
 *         &lt;element name="left" type="{}Proportion"/>
 *         &lt;element name="right" type="{}Proportion"/>
 *         &lt;element name="rear" type="{}Proportion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetPercentages", propOrder = {
    "front",
    "left",
    "right",
    "rear"
})
public class TargetPercentages {

    protected float front;
    protected float left;
    protected float right;
    protected float rear;
    private final transient FloatProperty frontProxy = new SimpleFloatProperty();
    private final transient FloatProperty leftProxy = new SimpleFloatProperty();
    private final transient FloatProperty rightProxy = new SimpleFloatProperty();
    private final transient FloatProperty rearProxy = new SimpleFloatProperty();

    /**
     * Define el valor de la propiedad front.
     * 
     */
    public void setFront(float value) {
        this.front = value;
        this.frontProxy.set(value);
    }

    /**
     * Define el valor de la propiedad left.
     * 
     */
    public void setLeft(float value) {
        this.left = value;
        this.leftProxy.set(value);
    }

    /**
     * Define el valor de la propiedad right.
     * 
     */
    public void setRight(float value) {
        this.right = value;
        this.rightProxy.set(value);
    }

    /**
     * Define el valor de la propiedad rear.
     * 
     */
    public void setRear(float value) {
        this.rear = value;
        this.rearProxy.set(value);
    }

    /**
     * Obtiene el valor de la propiedad front.
     * 
     */
    public float getFront() {
        return this.frontProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty frontProperty() {
        return this.frontProxy;
    }

    /**
     * Obtiene el valor de la propiedad left.
     * 
     */
    public float getLeft() {
        return this.leftProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty leftProperty() {
        return this.leftProxy;
    }

    /**
     * Obtiene el valor de la propiedad right.
     * 
     */
    public float getRight() {
        return this.rightProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rightProperty() {
        return this.rightProxy;
    }

    /**
     * Obtiene el valor de la propiedad rear.
     * 
     */
    public float getRear() {
        return this.rearProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rearProperty() {
        return this.rearProxy;
    }

}
