//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 04:34:30 AM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ListProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.collections.FXCollections;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for AmmoList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmmoList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ammo" type="{}AmmoQty" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class AmmoList {

    protected List<AmmoQty> ammo;

    /**
     * Gets the value of the ammo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ammo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmmo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmmoQty }
     * 
     * 
     */
    public List<AmmoQty> getAmmo() {
        if (ammo == null) {
            List backingList = new ArrayList<AmmoQty>();
            ammo = new SimpleListProperty<AmmoQty>(FXCollections.observableArrayList(backingList));
        } else {
            if (ammo instanceof ArrayList) {
                ammo = new SimpleListProperty<AmmoQty>(FXCollections.observableArrayList(ammo));
            }
        }
        SimpleListProperty<AmmoQty> ammoWrapper = ((SimpleListProperty<AmmoQty> ) this.ammo);
        return ammoWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<AmmoQty> ammoProperty() {
        return ((ListProperty<AmmoQty> ) this.ammo);
    }

    public void setAmmo(List<AmmoQty> ammo) {
        this.ammo = ammo;
    }

}
