//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 08:01:14 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import javax.xml.bind.annotation.XmlAttribute;


/**
 * <p>Java class for AmmoLoad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmmoLoad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="object-id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="load" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class AmmoLoad {

    protected int objectId;
    protected String name;
    protected int load;
    private final transient IntegerProperty objectIdProxy = new SimpleIntegerProperty();
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient IntegerProperty loadProxy = new SimpleIntegerProperty();

    /**
     * Sets the value of the objectId property.
     * 
     */
    @XmlAttribute(required = true, name = "object-id")
    public void setObjectId(int value) {
        this.objectId = value;
        this.objectIdProxy.set(value);
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @XmlAttribute(required = true, name = "name")
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the load property.
     * 
     */
    @XmlAttribute(required = true, name = "load")
    public void setLoad(int value) {
        this.load = value;
        this.loadProxy.set(value);
    }

    /**
     * Gets the value of the objectId property.
     * 
     */
    public int getObjectId() {
        return this.objectIdProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty objectIdProperty() {
        return this.objectIdProxy;
    }

    /**
     * Gets the value of the name property.
     * 
     */
    public String getName() {
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the load property.
     * 
     */
    public int getLoad() {
        return this.loadProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty loadProperty() {
        return this.loadProxy;
    }

}
