//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 08:01:14 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ListProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.collections.FXCollections;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArmamentList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArmamentList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="armament" type="{}Armament" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ArmamentList {

    protected List<Armament> armament;

    /**
     * Gets the value of the armament property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the armament property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArmament().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Armament }
     * 
     * 
     */
    public List<Armament> getArmament() {
        if (armament == null) {
            List backingList = new ArrayList<Armament>();
            armament = new SimpleListProperty<Armament>(FXCollections.observableArrayList(backingList));
        }
        SimpleListProperty<Armament> armamentWrapper = ((SimpleListProperty<Armament> ) this.armament);
        return armamentWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Armament> armamentProperty() {
        return ((ListProperty<Armament> ) this.armament);
    }

}
