//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 10:33:57 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefaultIconColors complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefaultIconColors">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="background-color" type="{}RGBColor"/>
 *         &lt;element name="background-dark-color" type="{}RGBColor"/>
 *         &lt;element name="background-light-color" type="{}RGBColor"/>
 *         &lt;element name="designation-color" type="{}RGBColor"/>
 *         &lt;element name="symbol-color" type="{}SymbolColor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultIconColors", propOrder = {
    "backgroundColor",
    "backgroundDarkColor",
    "backgroundLightColor",
    "designationColor",
    "symbolColor"
})
public class DefaultIconColors {

    @XmlElement(name = "background-color", required = true)
    protected RGBColor backgroundColor;
    @XmlElement(name = "background-dark-color", required = true)
    protected RGBColor backgroundDarkColor;
    @XmlElement(name = "background-light-color", required = true)
    protected RGBColor backgroundLightColor;
    @XmlElement(name = "designation-color", required = true)
    protected RGBColor designationColor;
    @XmlElement(name = "symbol-color", required = true)
    protected SymbolColor symbolColor;
    private final transient ObjectProperty<RGBColor> backgroundColorProxy = new SimpleObjectProperty<RGBColor>();
    private final transient ObjectProperty<RGBColor> backgroundDarkColorProxy = new SimpleObjectProperty<RGBColor>();
    private final transient ObjectProperty<RGBColor> backgroundLightColorProxy = new SimpleObjectProperty<RGBColor>();
    private final transient ObjectProperty<RGBColor> designationColorProxy = new SimpleObjectProperty<RGBColor>();
    private final transient ObjectProperty<SymbolColor> symbolColorProxy = new SimpleObjectProperty<SymbolColor>();

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.RGBColor }
     *     
     */
    public void setBackgroundColor(RGBColor value) {
        this.backgroundColor = value;
        this.backgroundColorProxy.set(value);
    }

    /**
     * Sets the value of the backgroundDarkColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.RGBColor }
     *     
     */
    public void setBackgroundDarkColor(RGBColor value) {
        this.backgroundDarkColor = value;
        this.backgroundDarkColorProxy.set(value);
    }

    /**
     * Sets the value of the backgroundLightColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.RGBColor }
     *     
     */
    public void setBackgroundLightColor(RGBColor value) {
        this.backgroundLightColor = value;
        this.backgroundLightColorProxy.set(value);
    }

    /**
     * Sets the value of the designationColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.RGBColor }
     *     
     */
    public void setDesignationColor(RGBColor value) {
        this.designationColor = value;
        this.designationColorProxy.set(value);
    }

    /**
     * Sets the value of the symbolColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.SymbolColor }
     *     
     */
    public void setSymbolColor(SymbolColor value) {
        this.symbolColor = value;
        this.symbolColorProxy.set(value);
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     */
    public RGBColor getBackgroundColor() {
        this.backgroundColorProxy.set(backgroundColor);
        return this.backgroundColorProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<RGBColor> backgroundColorProperty() {
        return this.backgroundColorProxy;
    }

    /**
     * Gets the value of the backgroundDarkColor property.
     * 
     */
    public RGBColor getBackgroundDarkColor() {
        this.backgroundDarkColorProxy.set(backgroundDarkColor);
        return this.backgroundDarkColorProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<RGBColor> backgroundDarkColorProperty() {
        return this.backgroundDarkColorProxy;
    }

    /**
     * Gets the value of the backgroundLightColor property.
     * 
     */
    public RGBColor getBackgroundLightColor() {
        this.backgroundLightColorProxy.set(backgroundLightColor);
        return this.backgroundLightColorProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<RGBColor> backgroundLightColorProperty() {
        return this.backgroundLightColorProxy;
    }

    /**
     * Gets the value of the designationColor property.
     * 
     */
    public RGBColor getDesignationColor() {
        this.designationColorProxy.set(designationColor);
        return this.designationColorProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<RGBColor> designationColorProperty() {
        return this.designationColorProxy;
    }

    /**
     * Gets the value of the symbolColor property.
     * 
     */
    public SymbolColor getSymbolColor() {
        this.symbolColorProxy.set(symbolColor);
        return this.symbolColorProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<SymbolColor> symbolColorProperty() {
        return this.symbolColorProxy;
    }

}
