//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 04:36:56 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeploymentDuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeploymentDuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="dug-in" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="entrenched" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="fortified" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class DeploymentDuration {

    protected XMLGregorianCalendar deployed;
    protected XMLGregorianCalendar dugIn;
    protected XMLGregorianCalendar entrenched;
    protected XMLGregorianCalendar fortified;
    private final transient ObjectProperty<XMLGregorianCalendar> deployedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> dugInProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> entrenchedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> fortifiedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();

    /**
     * Sets the value of the deployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    public void setDeployed(XMLGregorianCalendar value) {
        this.deployed = value;
        this.deployedProxy.set(value);
    }

    /**
     * Sets the value of the dugIn property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    @XmlElement(required = true, name = "dug-in")
    @XmlSchemaType(name = "time")
    public void setDugIn(XMLGregorianCalendar value) {
        this.dugIn = value;
        this.dugInProxy.set(value);
    }

    /**
     * Sets the value of the entrenched property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    public void setEntrenched(XMLGregorianCalendar value) {
        this.entrenched = value;
        this.entrenchedProxy.set(value);
    }

    /**
     * Sets the value of the fortified property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    public void setFortified(XMLGregorianCalendar value) {
        this.fortified = value;
        this.fortifiedProxy.set(value);
    }

    /**
     * Gets the value of the deployed property.
     * 
     */
    public XMLGregorianCalendar getDeployed() {
        return this.deployedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> deployedProperty() {
        return this.deployedProxy;
    }

    /**
     * Gets the value of the dugIn property.
     * 
     */
    public XMLGregorianCalendar getDugIn() {
        return this.dugInProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> dugInProperty() {
        return this.dugInProxy;
    }

    /**
     * Gets the value of the entrenched property.
     * 
     */
    public XMLGregorianCalendar getEntrenched() {
        return this.entrenchedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> entrenchedProperty() {
        return this.entrenchedProxy;
    }

    /**
     * Gets the value of the fortified property.
     * 
     */
    public XMLGregorianCalendar getFortified() {
        return this.fortifiedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<XMLGregorianCalendar> fortifiedProperty() {
        return this.fortifiedProxy;
    }

}
