//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 04:24:04 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeploymentDuration complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DeploymentDuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="dug-in" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="entrenched" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="fortified" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeploymentDuration", propOrder = {
        "deployed",
        "dugIn",
        "entrenched",
        "fortified"
})
public class DeploymentDuration {

    private final transient ObjectProperty<XMLGregorianCalendar> deployedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> dugInProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> entrenchedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    private final transient ObjectProperty<XMLGregorianCalendar> fortifiedProxy = new SimpleObjectProperty<XMLGregorianCalendar>();
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar deployed;
    @XmlElement(name = "dug-in", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dugIn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar entrenched;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar fortified;

    /**
     * Gets the value of the deployed property.
     */
    public XMLGregorianCalendar getDeployed() {
        if (this.deployedProxy.get() == null) {
            this.deployedProxy.set(deployed);
        }
        return this.deployedProxy.get();
    }

    /**
     * Sets the value of the deployed property.
     *
     * @param value allowed object is
     *              {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public void setDeployed(XMLGregorianCalendar value) {
        this.deployed = value;
        this.deployedProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<XMLGregorianCalendar> deployedProperty() {
        return this.deployedProxy;
    }

    /**
     * Gets the value of the dugIn property.
     */
    public XMLGregorianCalendar getDugIn() {
        if (this.dugInProxy.get() == null) {
            this.dugInProxy.set(dugIn);
        }
        return this.dugInProxy.get();
    }

    /**
     * Sets the value of the dugIn property.
     *
     * @param value allowed object is
     *              {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public void setDugIn(XMLGregorianCalendar value) {
        this.dugIn = value;
        this.dugInProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<XMLGregorianCalendar> dugInProperty() {
        return this.dugInProxy;
    }

    /**
     * Gets the value of the entrenched property.
     */
    public XMLGregorianCalendar getEntrenched() {
        if (this.entrenchedProxy.get() == null) {
            this.entrenchedProxy.set(entrenched);
        }
        return this.entrenchedProxy.get();
    }

    /**
     * Sets the value of the entrenched property.
     *
     * @param value allowed object is
     *              {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public void setEntrenched(XMLGregorianCalendar value) {
        this.entrenched = value;
        this.entrenchedProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<XMLGregorianCalendar> entrenchedProperty() {
        return this.entrenchedProxy;
    }

    /**
     * Gets the value of the fortified property.
     */
    public XMLGregorianCalendar getFortified() {
        if (this.fortifiedProxy.get() == null) {
            this.fortifiedProxy.set(fortified);
        }
        return this.fortifiedProxy.get();
    }

    /**
     * Sets the value of the fortified property.
     *
     * @param value allowed object is
     *              {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public void setFortified(XMLGregorianCalendar value) {
        this.fortified = value;
        this.fortifiedProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<XMLGregorianCalendar> fortifiedProperty() {
        return this.fortifiedProxy;
    }

}
