//
// This file was net.deludobellico.stabeditor.data.jaxb by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 08:18:10 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import java.util.ArrayList;
import java.util.List;
import javafx.beans.property.ListProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.collections.FXCollections;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}image" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}side" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;element ref="{}vehicle" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}weapon" maxOccurs="unbounded"/>
 *         &lt;element ref="{}radio" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ammo" maxOccurs="unbounded"/>
 *         &lt;element ref="{}formation-effects" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "image",
    "side",
    "vehicle",
    "weapon",
    "radio",
    "ammo",
    "formationEffects"
})
@XmlRootElement(name = "estab-data")
public class EstabData {

    protected List<Image> image;
    @XmlElement(required = true)
    protected List<Side> side;
    protected List<Vehicle> vehicle;
    @XmlElement(required = true)
    protected List<Weapon> weapon;
    protected List<Radio> radio;
    @XmlElement(required = true)
    protected List<Ammo> ammo;
    @XmlElement(name = "formation-effects", required = true)
    protected List<FormationEffects> formationEffects;
    @XmlAttribute(name = "version")
    protected Byte version;
    private final transient ObjectProperty<Byte> versionProxy = new SimpleObjectProperty<Byte>();

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVersion(Byte value) {
        this.version = value;
        this.versionProxy.set(value);
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     * 
     * 
     */
    public List<Image> getImage() {
        if (image == null) {
            List backingList = new ArrayList<Image>();
            image = new SimpleListProperty<Image>(FXCollections.observableArrayList(backingList));
        } else if (image instanceof ArrayList){
            image = new SimpleListProperty<Image>(FXCollections.observableArrayList(image));
        }
        SimpleListProperty<Image> imageWrapper = ((SimpleListProperty<Image> ) this.image);
        return imageWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Image> imageProperty() {
        return ((ListProperty<Image> ) this.image);
    }

    /**
     * Gets the value of the side property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the side property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSide().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Side }
     * 
     * 
     */
    public List<Side> getSide() {
        if (side == null) {
            List backingList = new ArrayList<Side>();
            side = new SimpleListProperty<Side>(FXCollections.observableArrayList(backingList));
        } else if (side instanceof ArrayList){
            side = new SimpleListProperty<Side>(FXCollections.observableArrayList(side));
        }
        SimpleListProperty<Side> sideWrapper = ((SimpleListProperty<Side> ) this.side);
        return sideWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Side> sideProperty() {
        return ((ListProperty<Side> ) this.side);
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vehicle }
     * 
     * 
     */
    public List<Vehicle> getVehicle() {
        if (vehicle == null) {
            List backingList = new ArrayList<Vehicle>();
            vehicle = new SimpleListProperty<Vehicle>(FXCollections.observableArrayList(backingList));
        } else if (vehicle instanceof ArrayList){
            vehicle = new SimpleListProperty<Vehicle>(FXCollections.observableArrayList(vehicle));
        }
        SimpleListProperty<Vehicle> vehicleWrapper = ((SimpleListProperty<Vehicle> ) this.vehicle);
        return vehicleWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Vehicle> vehicleProperty() {
        return ((ListProperty<Vehicle> ) this.vehicle);
    }

    /**
     * Gets the value of the weapon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the weapon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWeapon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Weapon }
     * 
     * 
     */
    public List<Weapon> getWeapon() {
        if (weapon == null) {
            List backingList = new ArrayList<Weapon>();
            weapon = new SimpleListProperty<Weapon>(FXCollections.observableArrayList(backingList));
        } else if (weapon instanceof ArrayList){
            weapon = new SimpleListProperty<Weapon>(FXCollections.observableArrayList(weapon));
        }
        SimpleListProperty<Weapon> weaponWrapper = ((SimpleListProperty<Weapon> ) this.weapon);
        return weaponWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Weapon> weaponProperty() {
        return ((ListProperty<Weapon> ) this.weapon);
    }

    /**
     * Gets the value of the radio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the radio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRadio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Radio }
     * 
     * 
     */
    public List<Radio> getRadio() {
        if (radio == null) {
            List backingList = new ArrayList<Radio>();
            radio = new SimpleListProperty<Radio>(FXCollections.observableArrayList(backingList));
        } else if (radio instanceof ArrayList){
            radio = new SimpleListProperty<Radio>(FXCollections.observableArrayList(radio));
        }
        SimpleListProperty<Radio> radioWrapper = ((SimpleListProperty<Radio> ) this.radio);
        return radioWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Radio> radioProperty() {
        return ((ListProperty<Radio> ) this.radio);
    }

    /**
     * Gets the value of the ammo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ammo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmmo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ammo }
     * 
     * 
     */
    public List<Ammo> getAmmo() {
        if (ammo == null) {
            List backingList = new ArrayList<Ammo>();
            ammo = new SimpleListProperty<Ammo>(FXCollections.observableArrayList(backingList));
        } else if (ammo instanceof ArrayList){
            ammo = new SimpleListProperty<Ammo>(FXCollections.observableArrayList(ammo));
        }
        SimpleListProperty<Ammo> ammoWrapper = ((SimpleListProperty<Ammo> ) this.ammo);
        return ammoWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Ammo> ammoProperty() {
        return ((ListProperty<Ammo> ) this.ammo);
    }

    /**
     * Gets the value of the formationEffects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formationEffects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormationEffects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormationEffects }
     * 
     * 
     */
    public List<FormationEffects> getFormationEffects() {
        if (formationEffects == null) {
            List backingList = new ArrayList<FormationEffects>();
            formationEffects = new SimpleListProperty<FormationEffects>(FXCollections.observableArrayList(backingList));
        } else if (formationEffects instanceof ArrayList){
            formationEffects = new SimpleListProperty<FormationEffects>(FXCollections.observableArrayList(formationEffects));
        }
        SimpleListProperty<FormationEffects> formationEffectsWrapper = ((SimpleListProperty<FormationEffects> ) this.formationEffects);
        return formationEffectsWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<FormationEffects> formationEffectsProperty() {
        return ((ListProperty<FormationEffects> ) this.formationEffects);
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public Byte getVersion() {
        if (this.versionProxy.get() == null) {
            this.versionProxy.set(version);
        }
        return this.versionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> versionProperty() {
        return this.versionProxy;
    }

}
