//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 02:15:22 AM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Force complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Force">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icon" type="{}Icon"/>
 *         &lt;element name="type" type="{}ForceType"/>
 *         &lt;element name="sub-type" type="{}ForceSubtype"/>
 *         &lt;element name="size" type="{}ForceSize"/>
 *         &lt;element name="combat-class" type="{}CombatClass"/>
 *         &lt;element name="target-class" type="{}TargetClass"/>
 *         &lt;element name="infantry-value" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="recon-value" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="engineering-value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="move-type" type="{}MoveType"/>
 *         &lt;element name="pers-qty" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="staff-capacity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="basics-qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="basics-consumption-rate-modifier" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="commander-rank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="fuel-qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="fuel-load" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="speed" type="{}SpeedData"/>
 *         &lt;element name="deployment-duration" type="{}DeploymentDuration"/>
 *         &lt;element name="ready-to-fire-duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ready-to-bombard-duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="equipment-list" type="{}EquipmentList"/>
 *         &lt;element name="ammo-list" type="{}AmmoList"/>
 *         &lt;element name="can-bombard" type="{}YesNo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Force", propOrder = {
    "name",
    "description",
    "icon",
    "type",
    "subType",
    "size",
    "combatClass",
    "targetClass",
    "infantryValue",
    "reconValue",
    "engineeringValue",
    "moveType",
    "persQty",
    "staffCapacity",
    "basicsQty",
    "basicsConsumptionRateModifier",
    "commanderRank",
    "fuelQty",
    "fuelLoad",
    "speed",
    "deploymentDuration",
    "readyToFireDuration",
    "readyToBombardDuration",
    "equipmentList",
    "ammoList",
    "canBombard"
})
public class Force {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Icon icon;
    @XmlElement(required = true)
    protected ForceType type;
    @XmlElement(name = "sub-type", required = true)
    protected ForceSubtype subType;
    @XmlElement(required = true)
    protected ForceSize size;
    @XmlElement(name = "combat-class", required = true)
    protected CombatClass combatClass;
    @XmlElement(name = "target-class", required = true)
    protected TargetClass targetClass;
    @XmlElement(name = "infantry-value")
    protected short infantryValue;
    @XmlElement(name = "recon-value")
    protected short reconValue;
    @XmlElement(name = "engineering-value")
    protected byte engineeringValue;
    @XmlElement(name = "move-type", required = true)
    protected MoveType moveType;
    @XmlElement(name = "pers-qty")
    protected short persQty;
    @XmlElement(name = "staff-capacity")
    protected byte staffCapacity;
    @XmlElement(name = "basics-qty")
    protected float basicsQty;
    @XmlElement(name = "basics-consumption-rate-modifier")
    protected float basicsConsumptionRateModifier;
    @XmlElement(name = "commander-rank")
    protected byte commanderRank;
    @XmlElement(name = "fuel-qty")
    protected float fuelQty;
    @XmlElement(name = "fuel-load")
    protected float fuelLoad;
    @XmlElement(required = true)
    protected SpeedData speed;
    @XmlElement(name = "deployment-duration", required = true)
    protected DeploymentDuration deploymentDuration;
    @XmlElement(name = "ready-to-fire-duration", required = true)
    protected String readyToFireDuration;
    @XmlElement(name = "ready-to-bombard-duration", required = true)
    protected String readyToBombardDuration;
    @XmlElement(name = "equipment-list", required = true)
    protected EquipmentList equipmentList;
    @XmlElement(name = "ammo-list", required = true)
    protected AmmoList ammoList;
    @XmlElement(name = "can-bombard", required = true)
    protected YesNo canBombard;
    @XmlAttribute(name = "id", required = true)
    protected short id;
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient StringProperty descriptionProxy = new SimpleStringProperty();
    private final transient ObjectProperty<Icon> iconProxy = new SimpleObjectProperty<Icon>();
    private final transient ObjectProperty<ForceType> typeProxy = new SimpleObjectProperty<ForceType>();
    private final transient ObjectProperty<ForceSubtype> subTypeProxy = new SimpleObjectProperty<ForceSubtype>();
    private final transient ObjectProperty<ForceSize> sizeProxy = new SimpleObjectProperty<ForceSize>();
    private final transient ObjectProperty<CombatClass> combatClassProxy = new SimpleObjectProperty<CombatClass>();
    private final transient ObjectProperty<TargetClass> targetClassProxy = new SimpleObjectProperty<TargetClass>();
    private final transient ObjectProperty<Short> infantryValueProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Short> reconValueProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Byte> engineeringValueProxy = new SimpleObjectProperty<Byte>();
    private final transient ObjectProperty<MoveType> moveTypeProxy = new SimpleObjectProperty<MoveType>();
    private final transient ObjectProperty<Short> persQtyProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Byte> staffCapacityProxy = new SimpleObjectProperty<Byte>();
    private final transient FloatProperty basicsQtyProxy = new SimpleFloatProperty();
    private final transient FloatProperty basicsConsumptionRateModifierProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<Byte> commanderRankProxy = new SimpleObjectProperty<Byte>();
    private final transient FloatProperty fuelQtyProxy = new SimpleFloatProperty();
    private final transient FloatProperty fuelLoadProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<SpeedData> speedProxy = new SimpleObjectProperty<SpeedData>();
    private final transient ObjectProperty<DeploymentDuration> deploymentDurationProxy = new SimpleObjectProperty<DeploymentDuration>();
    private final transient StringProperty readyToFireDurationProxy = new SimpleStringProperty();
    private final transient StringProperty readyToBombardDurationProxy = new SimpleStringProperty();
    private final transient ObjectProperty<EquipmentList> equipmentListProxy = new SimpleObjectProperty<EquipmentList>();
    private final transient ObjectProperty<AmmoList> ammoListProxy = new SimpleObjectProperty<AmmoList>();
    private final transient ObjectProperty<YesNo> canBombardProxy = new SimpleObjectProperty<YesNo>();
    private final transient ObjectProperty<Short> idProxy = new SimpleObjectProperty<Short>();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
        this.descriptionProxy.set(value);
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icon }
     *     
     */
    public void setIcon(Icon value) {
        this.icon = value;
        this.iconProxy.set(value);
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForceType }
     *     
     */
    public void setType(ForceType value) {
        this.type = value;
        this.typeProxy.set(value);
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForceSubtype }
     *     
     */
    public void setSubType(ForceSubtype value) {
        this.subType = value;
        this.subTypeProxy.set(value);
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForceSize }
     *     
     */
    public void setSize(ForceSize value) {
        this.size = value;
        this.sizeProxy.set(value);
    }

    /**
     * Sets the value of the combatClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CombatClass }
     *     
     */
    public void setCombatClass(CombatClass value) {
        this.combatClass = value;
        this.combatClassProxy.set(value);
    }

    /**
     * Sets the value of the targetClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetClass }
     *     
     */
    public void setTargetClass(TargetClass value) {
        this.targetClass = value;
        this.targetClassProxy.set(value);
    }

    /**
     * Sets the value of the infantryValue property.
     * 
     */
    public void setInfantryValue(short value) {
        this.infantryValue = value;
        this.infantryValueProxy.set(value);
    }

    /**
     * Sets the value of the reconValue property.
     * 
     */
    public void setReconValue(short value) {
        this.reconValue = value;
        this.reconValueProxy.set(value);
    }

    /**
     * Sets the value of the engineeringValue property.
     * 
     */
    public void setEngineeringValue(byte value) {
        this.engineeringValue = value;
        this.engineeringValueProxy.set(value);
    }

    /**
     * Sets the value of the moveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoveType }
     *     
     */
    public void setMoveType(MoveType value) {
        this.moveType = value;
        this.moveTypeProxy.set(value);
    }

    /**
     * Sets the value of the persQty property.
     * 
     */
    public void setPersQty(short value) {
        this.persQty = value;
        this.persQtyProxy.set(value);
    }

    /**
     * Sets the value of the staffCapacity property.
     * 
     */
    public void setStaffCapacity(byte value) {
        this.staffCapacity = value;
        this.staffCapacityProxy.set(value);
    }

    /**
     * Sets the value of the basicsQty property.
     * 
     */
    public void setBasicsQty(float value) {
        this.basicsQty = value;
        this.basicsQtyProxy.set(value);
    }

    /**
     * Sets the value of the basicsConsumptionRateModifier property.
     * 
     */
    public void setBasicsConsumptionRateModifier(float value) {
        this.basicsConsumptionRateModifier = value;
        this.basicsConsumptionRateModifierProxy.set(value);
    }

    /**
     * Sets the value of the commanderRank property.
     * 
     */
    public void setCommanderRank(byte value) {
        this.commanderRank = value;
        this.commanderRankProxy.set(value);
    }

    /**
     * Sets the value of the fuelQty property.
     * 
     */
    public void setFuelQty(float value) {
        this.fuelQty = value;
        this.fuelQtyProxy.set(value);
    }

    /**
     * Sets the value of the fuelLoad property.
     * 
     */
    public void setFuelLoad(float value) {
        this.fuelLoad = value;
        this.fuelLoadProxy.set(value);
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedData }
     *     
     */
    public void setSpeed(SpeedData value) {
        this.speed = value;
        this.speedProxy.set(value);
    }

    /**
     * Sets the value of the deploymentDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentDuration }
     *     
     */
    public void setDeploymentDuration(DeploymentDuration value) {
        this.deploymentDuration = value;
        this.deploymentDurationProxy.set(value);
    }

    /**
     * Sets the value of the readyToFireDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadyToFireDuration(String value) {
        this.readyToFireDuration = value;
        this.readyToFireDurationProxy.set(value);
    }

    /**
     * Sets the value of the readyToBombardDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadyToBombardDuration(String value) {
        this.readyToBombardDuration = value;
        this.readyToBombardDurationProxy.set(value);
    }

    /**
     * Sets the value of the equipmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentList }
     *     
     */
    public void setEquipmentList(EquipmentList value) {
        this.equipmentList = value;
        this.equipmentListProxy.set(value);
    }

    /**
     * Sets the value of the ammoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmmoList }
     *     
     */
    public void setAmmoList(AmmoList value) {
        this.ammoList = value;
        this.ammoListProxy.set(value);
    }

    /**
     * Sets the value of the canBombard property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setCanBombard(YesNo value) {
        this.canBombard = value;
        this.canBombardProxy.set(value);
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(short value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Gets the value of the name property.
     * 
     */
    public String getName() {
        if (this.nameProxy.get() == null) {
            this.nameProxy.set(name);
        }
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the description property.
     * 
     */
    public String getDescription() {
        if (this.descriptionProxy.get() == null) {
            this.descriptionProxy.set(description);
        }
        return this.descriptionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty descriptionProperty() {
        return this.descriptionProxy;
    }

    /**
     * Gets the value of the icon property.
     * 
     */
    public Icon getIcon() {
        if (this.iconProxy.get() == null) {
            this.iconProxy.set(icon);
        }
        return this.iconProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Icon> iconProperty() {
        return this.iconProxy;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public ForceType getType() {
        if (this.typeProxy.get() == null) {
            this.typeProxy.set(type);
        }
        return this.typeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceType> typeProperty() {
        return this.typeProxy;
    }

    /**
     * Gets the value of the subType property.
     * 
     */
    public ForceSubtype getSubType() {
        if (this.subTypeProxy.get() == null) {
            this.subTypeProxy.set(subType);
        }
        return this.subTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceSubtype> subTypeProperty() {
        return this.subTypeProxy;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public ForceSize getSize() {
        if (this.sizeProxy.get() == null) {
            this.sizeProxy.set(size);
        }
        return this.sizeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceSize> sizeProperty() {
        return this.sizeProxy;
    }

    /**
     * Gets the value of the combatClass property.
     * 
     */
    public CombatClass getCombatClass() {
        if (this.combatClassProxy.get() == null) {
            this.combatClassProxy.set(combatClass);
        }
        return this.combatClassProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<CombatClass> combatClassProperty() {
        return this.combatClassProxy;
    }

    /**
     * Gets the value of the targetClass property.
     * 
     */
    public TargetClass getTargetClass() {
        if (this.targetClassProxy.get() == null) {
            this.targetClassProxy.set(targetClass);
        }
        return this.targetClassProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<TargetClass> targetClassProperty() {
        return this.targetClassProxy;
    }

    /**
     * Gets the value of the infantryValue property.
     * 
     */
    public short getInfantryValue() {
        if (this.infantryValueProxy.get() == null) {
            this.infantryValueProxy.set(infantryValue);
        }
        return this.infantryValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> infantryValueProperty() {
        return this.infantryValueProxy;
    }

    /**
     * Gets the value of the reconValue property.
     * 
     */
    public short getReconValue() {
        if (this.reconValueProxy.get() == null) {
            this.reconValueProxy.set(reconValue);
        }
        return this.reconValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> reconValueProperty() {
        return this.reconValueProxy;
    }

    /**
     * Gets the value of the engineeringValue property.
     * 
     */
    public byte getEngineeringValue() {
        if (this.engineeringValueProxy.get() == null) {
            this.engineeringValueProxy.set(engineeringValue);
        }
        return this.engineeringValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> engineeringValueProperty() {
        return this.engineeringValueProxy;
    }

    /**
     * Gets the value of the moveType property.
     * 
     */
    public MoveType getMoveType() {
        if (this.moveTypeProxy.get() == null) {
            this.moveTypeProxy.set(moveType);
        }
        return this.moveTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<MoveType> moveTypeProperty() {
        return this.moveTypeProxy;
    }

    /**
     * Gets the value of the persQty property.
     * 
     */
    public short getPersQty() {
        if (this.persQtyProxy.get() == null) {
            this.persQtyProxy.set(persQty);
        }
        return this.persQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> persQtyProperty() {
        return this.persQtyProxy;
    }

    /**
     * Gets the value of the staffCapacity property.
     * 
     */
    public byte getStaffCapacity() {
        if (this.staffCapacityProxy.get() == null) {
            this.staffCapacityProxy.set(staffCapacity);
        }
        return this.staffCapacityProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> staffCapacityProperty() {
        return this.staffCapacityProxy;
    }

    /**
     * Gets the value of the basicsQty property.
     * 
     */
    public float getBasicsQty() {
        return this.basicsQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty basicsQtyProperty() {
        return this.basicsQtyProxy;
    }

    /**
     * Gets the value of the basicsConsumptionRateModifier property.
     * 
     */
    public float getBasicsConsumptionRateModifier() {
        return this.basicsConsumptionRateModifierProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty basicsConsumptionRateModifierProperty() {
        return this.basicsConsumptionRateModifierProxy;
    }

    /**
     * Gets the value of the commanderRank property.
     * 
     */
    public byte getCommanderRank() {
        if (this.commanderRankProxy.get() == null) {
            this.commanderRankProxy.set(commanderRank);
        }
        return this.commanderRankProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> commanderRankProperty() {
        return this.commanderRankProxy;
    }

    /**
     * Gets the value of the fuelQty property.
     * 
     */
    public float getFuelQty() {
        return this.fuelQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty fuelQtyProperty() {
        return this.fuelQtyProxy;
    }

    /**
     * Gets the value of the fuelLoad property.
     * 
     */
    public float getFuelLoad() {
        return this.fuelLoadProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty fuelLoadProperty() {
        return this.fuelLoadProxy;
    }

    /**
     * Gets the value of the speed property.
     * 
     */
    public SpeedData getSpeed() {
        if (this.speedProxy.get() == null) {
            this.speedProxy.set(speed);
        }
        return this.speedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<SpeedData> speedProperty() {
        return this.speedProxy;
    }

    /**
     * Gets the value of the deploymentDuration property.
     * 
     */
    public DeploymentDuration getDeploymentDuration() {
        if (this.deploymentDurationProxy.get() == null) {
            this.deploymentDurationProxy.set(deploymentDuration);
        }
        return this.deploymentDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<DeploymentDuration> deploymentDurationProperty() {
        return this.deploymentDurationProxy;
    }

    /**
     * Gets the value of the readyToFireDuration property.
     * 
     */
    public String getReadyToFireDuration() {
        if (this.readyToFireDurationProxy.get() == null) {
            this.readyToFireDurationProxy.set(readyToFireDuration);
        }
        return this.readyToFireDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty readyToFireDurationProperty() {
        return this.readyToFireDurationProxy;
    }

    /**
     * Gets the value of the readyToBombardDuration property.
     * 
     */
    public String getReadyToBombardDuration() {
        if (this.readyToBombardDurationProxy.get() == null) {
            this.readyToBombardDurationProxy.set(readyToBombardDuration);
        }
        return this.readyToBombardDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty readyToBombardDurationProperty() {
        return this.readyToBombardDurationProxy;
    }

    /**
     * Gets the value of the equipmentList property.
     * 
     */
    public EquipmentList getEquipmentList() {
        if (this.equipmentListProxy.get() == null) {
            this.equipmentListProxy.set(equipmentList);
        }
        return this.equipmentListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<EquipmentList> equipmentListProperty() {
        return this.equipmentListProxy;
    }

    /**
     * Gets the value of the ammoList property.
     * 
     */
    public AmmoList getAmmoList() {
        if (this.ammoListProxy.get() == null) {
            this.ammoListProxy.set(ammoList);
        }
        return this.ammoListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<AmmoList> ammoListProperty() {
        return this.ammoListProxy;
    }

    /**
     * Gets the value of the canBombard property.
     * 
     */
    public YesNo getCanBombard() {
        if (this.canBombardProxy.get() == null) {
            this.canBombardProxy.set(canBombard);
        }
        return this.canBombardProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<YesNo> canBombardProperty() {
        return this.canBombardProxy;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public short getId() {
        if (this.idProxy.get() == null) {
            this.idProxy.set(id);
        }
        return this.idProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> idProperty() {
        return this.idProxy;
    }

}
