//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 04:36:56 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.*;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;


/**
 * <p>Java class for Force complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Force">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="icon" type="{}Icon"/>
 *         &lt;element name="type" type="{}ForceType"/>
 *         &lt;element name="sub-type" type="{}ForceSubtype"/>
 *         &lt;element name="size" type="{}ForceSize"/>
 *         &lt;element name="combat-class" type="{}CombatClass"/>
 *         &lt;element name="target-class" type="{}TargetClass"/>
 *         &lt;element name="infantry-value" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="recon-value" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="engineering-value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="move-type" type="{}MoveType"/>
 *         &lt;element name="pers-qty" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="staff-capacity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="basics-qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="basics-consumption-rate-modifier" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="commander-rank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="fuel-qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="fuel-load" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="speed" type="{}SpeedData"/>
 *         &lt;element name="deployment-duration" type="{}DeploymentDuration"/>
 *         &lt;element name="ready-to-fire-duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ready-to-bombard-duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="equipment-list" type="{}EquipmentList"/>
 *         &lt;element name="ammo-list" type="{}AmmoList"/>
 *         &lt;element name="can-bombard" type="{}YesNo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Force {

    protected String name;
    protected String description;
    protected Icon icon;
    protected ForceType type;
    protected ForceSubtype subType;
    protected ForceSize size;
    protected CombatClass combatClass;
    protected TargetClass targetClass;
    protected short infantryValue;
    protected short reconValue;
    protected byte engineeringValue;
    protected MoveType moveType;
    protected short persQty;
    protected byte staffCapacity;
    protected float basicsQty;
    protected float basicsConsumptionRateModifier;
    protected byte commanderRank;
    protected float fuelQty;
    protected float fuelLoad;
    protected SpeedData speed;
    protected DeploymentDuration deploymentDuration;
    protected String readyToFireDuration;
    protected String readyToBombardDuration;
    protected EquipmentList equipmentList;
    protected AmmoList ammoList;
    protected YesNo canBombard;
    protected short id;
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient StringProperty descriptionProxy = new SimpleStringProperty();
    private final transient ObjectProperty<Icon> iconProxy = new SimpleObjectProperty<Icon>();
    private final transient ObjectProperty<ForceType> typeProxy = new SimpleObjectProperty<ForceType>();
    private final transient ObjectProperty<ForceSubtype> subTypeProxy = new SimpleObjectProperty<ForceSubtype>();
    private final transient ObjectProperty<ForceSize> sizeProxy = new SimpleObjectProperty<ForceSize>();
    private final transient ObjectProperty<CombatClass> combatClassProxy = new SimpleObjectProperty<CombatClass>();
    private final transient ObjectProperty<TargetClass> targetClassProxy = new SimpleObjectProperty<TargetClass>();
    private final transient ObjectProperty<Short> infantryValueProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Short> reconValueProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Byte> engineeringValueProxy = new SimpleObjectProperty<Byte>();
    private final transient ObjectProperty<MoveType> moveTypeProxy = new SimpleObjectProperty<MoveType>();
    private final transient ObjectProperty<Short> persQtyProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Byte> staffCapacityProxy = new SimpleObjectProperty<Byte>();
    private final transient FloatProperty basicsQtyProxy = new SimpleFloatProperty();
    private final transient FloatProperty basicsConsumptionRateModifierProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<Byte> commanderRankProxy = new SimpleObjectProperty<Byte>();
    private final transient FloatProperty fuelQtyProxy = new SimpleFloatProperty();
    private final transient FloatProperty fuelLoadProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<SpeedData> speedProxy = new SimpleObjectProperty<SpeedData>();
    private final transient ObjectProperty<DeploymentDuration> deploymentDurationProxy = new SimpleObjectProperty<DeploymentDuration>();
    private final transient StringProperty readyToFireDurationProxy = new SimpleStringProperty();
    private final transient StringProperty readyToBombardDurationProxy = new SimpleStringProperty();
    private final transient ObjectProperty<EquipmentList> equipmentListProxy = new SimpleObjectProperty<EquipmentList>();
    private final transient ObjectProperty<AmmoList> ammoListProxy = new SimpleObjectProperty<AmmoList>();
    private final transient ObjectProperty<YesNo> canBombardProxy = new SimpleObjectProperty<YesNo>();
    private final transient ObjectProperty<Short> idProxy = new SimpleObjectProperty<Short>();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @XmlElement(required = true)
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @XmlElement(required = true)
    public void setDescription(String value) {
        this.description = value;
        this.descriptionProxy.set(value);
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icon }
     *
     */
    @XmlElement(required = true)
    public void setIcon(Icon value) {
        this.icon = value;
        this.iconProxy.set(value);
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link ForceType }
     *
     */
    @XmlElement(required = true)
    public void setType(ForceType value) {
        this.type = value;
        this.typeProxy.set(value);
    }

    /**
     * Sets the value of the subType property.
     *
     * @param value
     *     allowed object is
     *     {@link ForceSubtype }
     *
     */
    @XmlElement(required = true, name = "sub-type")
    public void setSubType(ForceSubtype value) {
        this.subType = value;
        this.subTypeProxy.set(value);
    }

    /**
     * Sets the value of the size property.
     *
     * @param value
     *     allowed object is
     *     {@link ForceSize }
     *
     */
    @XmlElement(required = true)
    public void setSize(ForceSize value) {
        this.size = value;
        this.sizeProxy.set(value);
    }

    /**
     * Sets the value of the combatClass property.
     *
     * @param value
     *     allowed object is
     *     {@link CombatClass }
     *
     */
    @XmlElement(required = true, name = "combat-class")
    public void setCombatClass(CombatClass value) {
        this.combatClass = value;
        this.combatClassProxy.set(value);
    }

    /**
     * Sets the value of the targetClass property.
     *
     * @param value
     *     allowed object is
     *     {@link TargetClass }
     *
     */
    @XmlElement(required = true, name = "target-class")
    public void setTargetClass(TargetClass value) {
        this.targetClass = value;
        this.targetClassProxy.set(value);
    }

    /**
     * Sets the value of the infantryValue property.
     *
     */
    @XmlElement(name = "infantry-value")
    public void setInfantryValue(short value) {
        this.infantryValue = value;
        this.infantryValueProxy.set(value);
    }

    /**
     * Sets the value of the reconValue property.
     *
     */
    @XmlElement(name = "recon-value")
    public void setReconValue(short value) {
        this.reconValue = value;
        this.reconValueProxy.set(value);
    }

    /**
     * Sets the value of the engineeringValue property.
     *
     */
    @XmlElement(name = "engineering-value")
    public void setEngineeringValue(byte value) {
        this.engineeringValue = value;
        this.engineeringValueProxy.set(value);
    }

    /**
     * Sets the value of the moveType property.
     *
     * @param value
     *     allowed object is
     *     {@link MoveType }
     *
     */
    @XmlElement(required = true, name = "move-type")
    public void setMoveType(MoveType value) {
        this.moveType = value;
        this.moveTypeProxy.set(value);
    }

    /**
     * Sets the value of the persQty property.
     *
     */
    @XmlElement(name = "pers-qty")
    public void setPersQty(short value) {
        this.persQty = value;
        this.persQtyProxy.set(value);
    }

    /**
     * Sets the value of the staffCapacity property.
     *
     */
    @XmlElement(name = "staff-capacity")
    public void setStaffCapacity(byte value) {
        this.staffCapacity = value;
        this.staffCapacityProxy.set(value);
    }

    /**
     * Sets the value of the basicsQty property.
     *
     */
    @XmlElement(name = "basics-qty")
    public void setBasicsQty(float value) {
        this.basicsQty = value;
        this.basicsQtyProxy.set(value);
    }

    /**
     * Sets the value of the basicsConsumptionRateModifier property.
     *
     */
    @XmlElement(name = "basics-consumption-rate-modifier")
    public void setBasicsConsumptionRateModifier(float value) {
        this.basicsConsumptionRateModifier = value;
        this.basicsConsumptionRateModifierProxy.set(value);
    }

    /**
     * Sets the value of the commanderRank property.
     *
     */
    @XmlElement(name = "commander-rank")
    public void setCommanderRank(byte value) {
        this.commanderRank = value;
        this.commanderRankProxy.set(value);
    }

    /**
     * Sets the value of the fuelQty property.
     *
     */
    @XmlElement(name = "fuel-qty")
    public void setFuelQty(float value) {
        this.fuelQty = value;
        this.fuelQtyProxy.set(value);
    }

    /**
     * Sets the value of the fuelLoad property.
     *
     */
    @XmlElement(name = "fuel-load")
    public void setFuelLoad(float value) {
        this.fuelLoad = value;
        this.fuelLoadProxy.set(value);
    }

    /**
     * Sets the value of the speed property.
     *
     * @param value
     *     allowed object is
     *     {@link SpeedData }
     *
     */
    @XmlElement(required = true)
    public void setSpeed(SpeedData value) {
        this.speed = value;
        this.speedProxy.set(value);
    }

    /**
     * Sets the value of the deploymentDuration property.
     *
     * @param value
     *     allowed object is
     *     {@link DeploymentDuration }
     *
     */
    @XmlElement(required = true, name = "deployment-duration")
    public void setDeploymentDuration(DeploymentDuration value) {
        this.deploymentDuration = value;
        this.deploymentDurationProxy.set(value);
    }

    /**
     * Sets the value of the readyToFireDuration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @XmlElement(required = true, name = "ready-to-fire-duration")
    public void setReadyToFireDuration(String value) {
        this.readyToFireDuration = value;
        this.readyToFireDurationProxy.set(value);
    }

    /**
     * Sets the value of the readyToBombardDuration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @XmlElement(required = true, name = "ready-to-bombard-duration")
    public void setReadyToBombardDuration(String value) {
        this.readyToBombardDuration = value;
        this.readyToBombardDurationProxy.set(value);
    }

    /**
     * Sets the value of the equipmentList property.
     *
     * @param value
     *     allowed object is
     *     {@link EquipmentList }
     *
     */
    @XmlElement(required = true, name = "equipment-list")
    public void setEquipmentList(EquipmentList value) {
        this.equipmentList = value;
        this.equipmentListProxy.set(value);
    }

    /**
     * Sets the value of the ammoList property.
     *
     * @param value
     *     allowed object is
     *     {@link AmmoList }
     *
     */
    @XmlElement(required = true, name = "ammo-list")
    public void setAmmoList(AmmoList value) {
        this.ammoList = value;
        this.ammoListProxy.set(value);
    }

    /**
     * Sets the value of the canBombard property.
     *
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    @XmlElement(required = true, name = "can-bombard")
    public void setCanBombard(YesNo value) {
        this.canBombard = value;
        this.canBombardProxy.set(value);
    }

    /**
     * Sets the value of the id property.
     * 
     */
    @XmlAttribute(required = true, name = "id")
    public void setId(short value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Gets the value of the name property.
     * 
     */
    public String getName() {
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the description property.
     * 
     */
    public String getDescription() {
        return this.descriptionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty descriptionProperty() {
        return this.descriptionProxy;
    }

    /**
     * Gets the value of the icon property.
     * 
     */
    public Icon getIcon() {
        return this.iconProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Icon> iconProperty() {
        return this.iconProxy;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public ForceType getType() {
        return this.typeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceType> typeProperty() {
        return this.typeProxy;
    }

    /**
     * Gets the value of the subType property.
     * 
     */
    public ForceSubtype getSubType() {
        return this.subTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceSubtype> subTypeProperty() {
        return this.subTypeProxy;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public ForceSize getSize() {
        return this.sizeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<ForceSize> sizeProperty() {
        return this.sizeProxy;
    }

    /**
     * Gets the value of the combatClass property.
     * 
     */
    public CombatClass getCombatClass() {
        return this.combatClassProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<CombatClass> combatClassProperty() {
        return this.combatClassProxy;
    }

    /**
     * Gets the value of the targetClass property.
     * 
     */
    public TargetClass getTargetClass() {
        return this.targetClassProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<TargetClass> targetClassProperty() {
        return this.targetClassProxy;
    }

    /**
     * Gets the value of the infantryValue property.
     * 
     */
    public short getInfantryValue() {
        return this.infantryValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> infantryValueProperty() {
        return this.infantryValueProxy;
    }

    /**
     * Gets the value of the reconValue property.
     * 
     */
    public short getReconValue() {
        return this.reconValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> reconValueProperty() {
        return this.reconValueProxy;
    }

    /**
     * Gets the value of the engineeringValue property.
     * 
     */
    public byte getEngineeringValue() {
        return this.engineeringValueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> engineeringValueProperty() {
        return this.engineeringValueProxy;
    }

    /**
     * Gets the value of the moveType property.
     * 
     */
    public MoveType getMoveType() {
        return this.moveTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<MoveType> moveTypeProperty() {
        return this.moveTypeProxy;
    }

    /**
     * Gets the value of the persQty property.
     * 
     */
    public short getPersQty() {
        return this.persQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> persQtyProperty() {
        return this.persQtyProxy;
    }

    /**
     * Gets the value of the staffCapacity property.
     * 
     */
    public byte getStaffCapacity() {
        return this.staffCapacityProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> staffCapacityProperty() {
        return this.staffCapacityProxy;
    }

    /**
     * Gets the value of the basicsQty property.
     * 
     */
    public float getBasicsQty() {
        return this.basicsQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty basicsQtyProperty() {
        return this.basicsQtyProxy;
    }

    /**
     * Gets the value of the basicsConsumptionRateModifier property.
     * 
     */
    public float getBasicsConsumptionRateModifier() {
        return this.basicsConsumptionRateModifierProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty basicsConsumptionRateModifierProperty() {
        return this.basicsConsumptionRateModifierProxy;
    }

    /**
     * Gets the value of the commanderRank property.
     * 
     */
    public byte getCommanderRank() {
        return this.commanderRankProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> commanderRankProperty() {
        return this.commanderRankProxy;
    }

    /**
     * Gets the value of the fuelQty property.
     * 
     */
    public float getFuelQty() {
        return this.fuelQtyProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty fuelQtyProperty() {
        return this.fuelQtyProxy;
    }

    /**
     * Gets the value of the fuelLoad property.
     * 
     */
    public float getFuelLoad() {
        return this.fuelLoadProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty fuelLoadProperty() {
        return this.fuelLoadProxy;
    }

    /**
     * Gets the value of the speed property.
     * 
     */
    public SpeedData getSpeed() {
        return this.speedProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<SpeedData> speedProperty() {
        return this.speedProxy;
    }

    /**
     * Gets the value of the deploymentDuration property.
     * 
     */
    public DeploymentDuration getDeploymentDuration() {
        return this.deploymentDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<DeploymentDuration> deploymentDurationProperty() {
        return this.deploymentDurationProxy;
    }

    /**
     * Gets the value of the readyToFireDuration property.
     * 
     */
    public String getReadyToFireDuration() {
        return this.readyToFireDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty readyToFireDurationProperty() {
        return this.readyToFireDurationProxy;
    }

    /**
     * Gets the value of the readyToBombardDuration property.
     * 
     */
    public String getReadyToBombardDuration() {
        return this.readyToBombardDurationProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty readyToBombardDurationProperty() {
        return this.readyToBombardDurationProxy;
    }

    /**
     * Gets the value of the equipmentList property.
     * 
     */
    public EquipmentList getEquipmentList() {
        return this.equipmentListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<EquipmentList> equipmentListProperty() {
        return this.equipmentListProxy;
    }

    /**
     * Gets the value of the ammoList property.
     * 
     */
    public AmmoList getAmmoList() {
        return this.ammoListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<AmmoList> ammoListProperty() {
        return this.ammoListProxy;
    }

    /**
     * Gets the value of the canBombard property.
     * 
     */
    public YesNo getCanBombard() {
        return this.canBombardProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<YesNo> canBombardProperty() {
        return this.canBombardProxy;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public short getId() {
        return this.idProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> idProperty() {
        return this.idProxy;
    }

}
