//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 04:24:04 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for FormationEffects complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="FormationEffects">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moving-cohesion-level" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="frontage-per-man" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="depth-per-man" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="firing-percentages" type="{}FiringPercentages"/>
 *         &lt;element name="target-percentages" type="{}TargetPercentages"/>
 *         &lt;element name="security" type="{}FormationSecurity"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="type" use="required" type="{}FormationType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormationEffects", propOrder = {
        "movingCohesionLevel",
        "frontagePerMan",
        "depthPerMan",
        "firingPercentages",
        "targetPercentages",
        "security"
})
public class FormationEffects {

    private final transient FloatProperty movingCohesionLevelProxy = new SimpleFloatProperty();
    private final transient FloatProperty frontagePerManProxy = new SimpleFloatProperty();
    private final transient FloatProperty depthPerManProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<FiringPercentages> firingPercentagesProxy = new SimpleObjectProperty<FiringPercentages>();
    private final transient ObjectProperty<TargetPercentages> targetPercentagesProxy = new SimpleObjectProperty<TargetPercentages>();
    private final transient ObjectProperty<FormationSecurity> securityProxy = new SimpleObjectProperty<FormationSecurity>();
    private final transient ObjectProperty<Short> idProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<FormationType> typeProxy = new SimpleObjectProperty<FormationType>();
    @XmlElement(name = "moving-cohesion-level")
    protected float movingCohesionLevel;
    @XmlElement(name = "frontage-per-man")
    protected float frontagePerMan;
    @XmlElement(name = "depth-per-man")
    protected float depthPerMan;
    @XmlElement(name = "firing-percentages", required = true)
    protected FiringPercentages firingPercentages;
    @XmlElement(name = "target-percentages", required = true)
    protected TargetPercentages targetPercentages;
    @XmlElement(required = true)
    protected FormationSecurity security;
    @XmlAttribute(name = "id", required = true)
    protected short id;
    @XmlAttribute(name = "type", required = true)
    protected FormationType type;

    /**
     * Gets the value of the movingCohesionLevel property.
     */
    public float getMovingCohesionLevel() {
        if (this.movingCohesionLevelProxy.get() == 0) {
            this.movingCohesionLevelProxy.set(movingCohesionLevel);
        }
        return this.movingCohesionLevelProxy.get();
    }

    /**
     * Sets the value of the movingCohesionLevel property.
     */
    public void setMovingCohesionLevel(float value) {
        this.movingCohesionLevel = value;
        this.movingCohesionLevelProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty movingCohesionLevelProperty() {
        return this.movingCohesionLevelProxy;
    }

    /**
     * Gets the value of the frontagePerMan property.
     */
    public float getFrontagePerMan() {
        if (this.frontagePerManProxy.get() == 0) {
            this.frontagePerManProxy.set(frontagePerMan);
        }
        return this.frontagePerManProxy.get();
    }

    /**
     * Sets the value of the frontagePerMan property.
     */
    public void setFrontagePerMan(float value) {
        this.frontagePerMan = value;
        this.frontagePerManProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty frontagePerManProperty() {
        return this.frontagePerManProxy;
    }

    /**
     * Gets the value of the depthPerMan property.
     */
    public float getDepthPerMan() {
        if (this.depthPerManProxy.get() == 0) {
            this.depthPerManProxy.set(depthPerMan);
        }
        return this.depthPerManProxy.get();
    }

    /**
     * Sets the value of the depthPerMan property.
     */
    public void setDepthPerMan(float value) {
        this.depthPerMan = value;
        this.depthPerManProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty depthPerManProperty() {
        return this.depthPerManProxy;
    }

    /**
     * Gets the value of the firingPercentages property.
     */
    public FiringPercentages getFiringPercentages() {
        if (this.firingPercentagesProxy.get() == null) {
            this.firingPercentagesProxy.set(firingPercentages);
        }
        return this.firingPercentagesProxy.get();
    }

    /**
     * Sets the value of the firingPercentages property.
     *
     * @param value allowed object is
     *              {@link FiringPercentages }
     */
    public void setFiringPercentages(FiringPercentages value) {
        this.firingPercentages = value;
        this.firingPercentagesProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<FiringPercentages> firingPercentagesProperty() {
        return this.firingPercentagesProxy;
    }

    /**
     * Gets the value of the targetPercentages property.
     */
    public TargetPercentages getTargetPercentages() {
        if (this.targetPercentagesProxy.get() == null) {
            this.targetPercentagesProxy.set(targetPercentages);
        }
        return this.targetPercentagesProxy.get();
    }

    /**
     * Sets the value of the targetPercentages property.
     *
     * @param value allowed object is
     *              {@link TargetPercentages }
     */
    public void setTargetPercentages(TargetPercentages value) {
        this.targetPercentages = value;
        this.targetPercentagesProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<TargetPercentages> targetPercentagesProperty() {
        return this.targetPercentagesProxy;
    }

    /**
     * Gets the value of the security property.
     */
    public FormationSecurity getSecurity() {
        if (this.securityProxy.get() == null) {
            this.securityProxy.set(security);
        }
        return this.securityProxy.get();
    }

    /**
     * Sets the value of the security property.
     *
     * @param value allowed object is
     *              {@link FormationSecurity }
     */
    public void setSecurity(FormationSecurity value) {
        this.security = value;
        this.securityProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<FormationSecurity> securityProperty() {
        return this.securityProxy;
    }

    /**
     * Gets the value of the id property.
     */
    public short getId() {
        if (this.idProxy.get() == null) {
            this.idProxy.set(id);
        }
        return this.idProxy.get();
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(short value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<Short> idProperty() {
        return this.idProxy;
    }

    /**
     * Gets the value of the type property.
     */
    public FormationType getType() {
        if (this.typeProxy.get() == null) {
            this.typeProxy.set(type);
        }
        return this.typeProxy.get();
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link FormationType }
     */
    public void setType(FormationType value) {
        this.type = value;
        this.typeProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<FormationType> typeProperty() {
        return this.typeProxy;
    }

}
