//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 10:33:57 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.deludobellico.stabeditor.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Image_QNAME = new QName("", "image");
    private final static QName _Weapon_QNAME = new QName("", "weapon");
    private final static QName _Side_QNAME = new QName("", "side");
    private final static QName _Ammo_QNAME = new QName("", "ammo");
    private final static QName _FormationEffects_QNAME = new QName("", "formation-effects");
    private final static QName _Vehicle_QNAME = new QName("", "vehicle");
    private final static QName _Radio_QNAME = new QName("", "radio");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.deludobellico.stabeditor.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.EstabData }
     * 
     */
    public EstabData createEstabData() {
        return new EstabData();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Side }
     * 
     */
    public Side createSide() {
        return new Side();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Weapon }
     * 
     */
    public Weapon createWeapon() {
        return new Weapon();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Radio }
     * 
     */
    public Radio createRadio() {
        return new Radio();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Ammo }
     * 
     */
    public Ammo createAmmo() {
        return new Ammo();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.FormationEffects }
     * 
     */
    public FormationEffects createFormationEffects() {
        return new FormationEffects();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.AmmoLoad }
     * 
     */
    public AmmoLoad createAmmoLoad() {
        return new AmmoLoad();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.FormationSecurity }
     * 
     */
    public FormationSecurity createFormationSecurity() {
        return new FormationSecurity();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.RankList }
     * 
     */
    public RankList createRankList() {
        return new RankList();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.TargetPercentages }
     * 
     */
    public TargetPercentages createTargetPercentages() {
        return new TargetPercentages();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.ROF }
     * 
     */
    public ROF createROF() {
        return new ROF();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.VehicleSize }
     * 
     */
    public VehicleSize createVehicleSize() {
        return new VehicleSize();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Icon }
     * 
     */
    public Icon createIcon() {
        return new Icon();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Performance }
     * 
     */
    public Performance createPerformance() {
        return new Performance();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Armament }
     * 
     */
    public Armament createArmament() {
        return new Armament();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.FuelConsumption }
     * 
     */
    public FuelConsumption createFuelConsumption() {
        return new FuelConsumption();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Nation }
     * 
     */
    public Nation createNation() {
        return new Nation();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.AmmoQty }
     * 
     */
    public AmmoQty createAmmoQty() {
        return new AmmoQty();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Insignia }
     * 
     */
    public Insignia createInsignia() {
        return new Insignia();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Force }
     * 
     */
    public Force createForce() {
        return new Force();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.RGBColor }
     * 
     */
    public RGBColor createRGBColor() {
        return new RGBColor();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.RangeTable }
     * 
     */
    public RangeTable createRangeTable() {
        return new RangeTable();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.VehicleSpeeds }
     * 
     */
    public VehicleSpeeds createVehicleSpeeds() {
        return new VehicleSpeeds();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.FiringPercentages }
     * 
     */
    public FiringPercentages createFiringPercentages() {
        return new FiringPercentages();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.DeploymentDuration }
     * 
     */
    public DeploymentDuration createDeploymentDuration() {
        return new DeploymentDuration();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.ArmamentList }
     * 
     */
    public ArmamentList createArmamentList() {
        return new ArmamentList();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Armor }
     * 
     */
    public Armor createArmor() {
        return new Armor();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.AmmoList }
     * 
     */
    public AmmoList createAmmoList() {
        return new AmmoList();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.PerformanceList }
     * 
     */
    public PerformanceList createPerformanceList() {
        return new PerformanceList();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.RadioSize }
     * 
     */
    public RadioSize createRadioSize() {
        return new RadioSize();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Rank }
     * 
     */
    public Rank createRank() {
        return new Rank();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.EquipmentList }
     * 
     */
    public EquipmentList createEquipmentList() {
        return new EquipmentList();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.RangeItem }
     * 
     */
    public RangeItem createRangeItem() {
        return new RangeItem();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.SpeedData }
     * 
     */
    public SpeedData createSpeedData() {
        return new SpeedData();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.DefaultIconColors }
     * 
     */
    public DefaultIconColors createDefaultIconColors() {
        return new DefaultIconColors();
    }

    /**
     * Create an instance of {@link net.deludobellico.stabeditor.data.jaxb.WeaponSize }
     * 
     */
    public WeaponSize createWeaponSize() {
        return new WeaponSize();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image")
    public JAXBElement<Image> createImage(Image value) {
        return new JAXBElement<Image>(_Image_QNAME, Image.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Weapon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "weapon")
    public JAXBElement<Weapon> createWeapon(Weapon value) {
        return new JAXBElement<Weapon>(_Weapon_QNAME, Weapon.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Side }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "side")
    public JAXBElement<Side> createSide(Side value) {
        return new JAXBElement<Side>(_Side_QNAME, Side.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Ammo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ammo")
    public JAXBElement<Ammo> createAmmo(Ammo value) {
        return new JAXBElement<Ammo>(_Ammo_QNAME, Ammo.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.FormationEffects }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "formation-effects")
    public JAXBElement<FormationEffects> createFormationEffects(FormationEffects value) {
        return new JAXBElement<FormationEffects>(_FormationEffects_QNAME, FormationEffects.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Vehicle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vehicle")
    public JAXBElement<Vehicle> createVehicle(Vehicle value) {
        return new JAXBElement<Vehicle>(_Vehicle_QNAME, Vehicle.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link net.deludobellico.stabeditor.data.jaxb.Radio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "radio")
    public JAXBElement<Radio> createRadio(Radio value) {
        return new JAXBElement<Radio>(_Radio_QNAME, Radio.class, null, value);
    }

}
