//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 10:33:57 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Radio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Radio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture-filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{}RadioSize"/>
 *         &lt;element name="crew" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reliability" type="{}Proportion"/>
 *         &lt;element name="armaments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="net-type" type="{}NetType"/>
 *         &lt;element name="freq-type" type="{}FreqType"/>
 *         &lt;element name="max-range" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="gain" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Radio", propOrder = {
    "name",
    "description",
    "picture",
    "pictureFilename",
    "size",
    "crew",
    "reliability",
    "armaments",
    "netType",
    "freqType",
    "maxRange",
    "gain"
})
public class Radio {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String picture;
    @XmlElement(name = "picture-filename", required = true)
    protected String pictureFilename;
    @XmlElement(required = true)
    protected RadioSize size;
    @XmlElement(required = true)
    protected String crew;
    protected float reliability;
    @XmlElement(required = true)
    protected String armaments;
    @XmlElement(name = "net-type", required = true)
    protected NetType netType;
    @XmlElement(name = "freq-type", required = true)
    protected FreqType freqType;
    @XmlElement(name = "max-range")
    protected short maxRange;
    protected float gain;
    @XmlAttribute(name = "id", required = true)
    protected short id;
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient StringProperty descriptionProxy = new SimpleStringProperty();
    private final transient StringProperty pictureProxy = new SimpleStringProperty();
    private final transient StringProperty pictureFilenameProxy = new SimpleStringProperty();
    private final transient ObjectProperty<RadioSize> sizeProxy = new SimpleObjectProperty<RadioSize>();
    private final transient StringProperty crewProxy = new SimpleStringProperty();
    private final transient FloatProperty reliabilityProxy = new SimpleFloatProperty();
    private final transient StringProperty armamentsProxy = new SimpleStringProperty();
    private final transient ObjectProperty<NetType> netTypeProxy = new SimpleObjectProperty<NetType>();
    private final transient ObjectProperty<FreqType> freqTypeProxy = new SimpleObjectProperty<FreqType>();
    private final transient ObjectProperty<Short> maxRangeProxy = new SimpleObjectProperty<Short>();
    private final transient FloatProperty gainProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<Short> idProxy = new SimpleObjectProperty<Short>();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
        this.descriptionProxy.set(value);
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicture(String value) {
        this.picture = value;
        this.pictureProxy.set(value);
    }

    /**
     * Sets the value of the pictureFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureFilename(String value) {
        this.pictureFilename = value;
        this.pictureFilenameProxy.set(value);
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.RadioSize }
     *     
     */
    public void setSize(RadioSize value) {
        this.size = value;
        this.sizeProxy.set(value);
    }

    /**
     * Sets the value of the crew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrew(String value) {
        this.crew = value;
        this.crewProxy.set(value);
    }

    /**
     * Sets the value of the reliability property.
     * 
     */
    public void setReliability(float value) {
        this.reliability = value;
        this.reliabilityProxy.set(value);
    }

    /**
     * Sets the value of the armaments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArmaments(String value) {
        this.armaments = value;
        this.armamentsProxy.set(value);
    }

    /**
     * Sets the value of the netType property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.NetType }
     *     
     */
    public void setNetType(NetType value) {
        this.netType = value;
        this.netTypeProxy.set(value);
    }

    /**
     * Sets the value of the freqType property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.FreqType }
     *     
     */
    public void setFreqType(FreqType value) {
        this.freqType = value;
        this.freqTypeProxy.set(value);
    }

    /**
     * Sets the value of the maxRange property.
     * 
     */
    public void setMaxRange(short value) {
        this.maxRange = value;
        this.maxRangeProxy.set(value);
    }

    /**
     * Sets the value of the gain property.
     * 
     */
    public void setGain(float value) {
        this.gain = value;
        this.gainProxy.set(value);
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(short value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Gets the value of the name property.
     * 
     */
    public String getName() {
        this.nameProxy.set(name);
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the description property.
     * 
     */
    public String getDescription() {
        this.descriptionProxy.set(description);
        return this.descriptionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty descriptionProperty() {
        return this.descriptionProxy;
    }

    /**
     * Gets the value of the picture property.
     * 
     */
    public String getPicture() {
        this.pictureProxy.set(picture);
        return this.pictureProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty pictureProperty() {
        return this.pictureProxy;
    }

    /**
     * Gets the value of the pictureFilename property.
     * 
     */
    public String getPictureFilename() {
        this.pictureFilenameProxy.set(pictureFilename);
        return this.pictureFilenameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty pictureFilenameProperty() {
        return this.pictureFilenameProxy;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public RadioSize getSize() {
        this.sizeProxy.set(size);
        return this.sizeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<RadioSize> sizeProperty() {
        return this.sizeProxy;
    }

    /**
     * Gets the value of the crew property.
     * 
     */
    public String getCrew() {
        this.crewProxy.set(crew);
        return this.crewProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty crewProperty() {
        return this.crewProxy;
    }

    /**
     * Gets the value of the reliability property.
     * 
     */
    public float getReliability() {
        this.reliabilityProxy.set(reliability);
        return this.reliabilityProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty reliabilityProperty() {
        return this.reliabilityProxy;
    }

    /**
     * Gets the value of the armaments property.
     * 
     */
    public String getArmaments() {
        this.armamentsProxy.set(armaments);
        return this.armamentsProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty armamentsProperty() {
        return this.armamentsProxy;
    }

    /**
     * Gets the value of the netType property.
     * 
     */
    public NetType getNetType() {
        this.netTypeProxy.set(netType);
        return this.netTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<NetType> netTypeProperty() {
        return this.netTypeProxy;
    }

    /**
     * Gets the value of the freqType property.
     * 
     */
    public FreqType getFreqType() {
        this.freqTypeProxy.set(freqType);
        return this.freqTypeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<FreqType> freqTypeProperty() {
        return this.freqTypeProxy;
    }

    /**
     * Gets the value of the maxRange property.
     * 
     */
    public short getMaxRange() {
        this.maxRangeProxy.set(maxRange);
        return this.maxRangeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> maxRangeProperty() {
        return this.maxRangeProxy;
    }

    /**
     * Gets the value of the gain property.
     * 
     */
    public float getGain() {
        this.gainProxy.set(gain);
        return this.gainProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty gainProperty() {
        return this.gainProxy;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public short getId() {
        this.idProxy.set(id);
        return this.idProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> idProperty() {
        return this.idProxy;
    }

}
