//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 04:24:04 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RadioSize complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="RadioSize">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="weight" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioSize")
public class RadioSize {

    private final transient FloatProperty widthProxy = new SimpleFloatProperty();
    private final transient FloatProperty heightProxy = new SimpleFloatProperty();
    private final transient FloatProperty lengthProxy = new SimpleFloatProperty();
    private final transient FloatProperty weightProxy = new SimpleFloatProperty();
    @XmlAttribute(name = "width", required = true)
    protected float width;
    @XmlAttribute(name = "height", required = true)
    protected float height;
    @XmlAttribute(name = "length", required = true)
    protected float length;
    @XmlAttribute(name = "weight", required = true)
    protected float weight;

    /**
     * Gets the value of the width property.
     */
    public float getWidth() {
        if (this.widthProxy.get() == 0) {
            this.widthProxy.set(width);
        }
        return this.widthProxy.get();
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(float value) {
        this.width = value;
        this.widthProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty widthProperty() {
        return this.widthProxy;
    }

    /**
     * Gets the value of the height property.
     */
    public float getHeight() {
        if (this.heightProxy.get() == 0) {
            this.heightProxy.set(height);
        }
        return this.heightProxy.get();
    }

    /**
     * Sets the value of the height property.
     */
    public void setHeight(float value) {
        this.height = value;
        this.heightProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty heightProperty() {
        return this.heightProxy;
    }

    /**
     * Gets the value of the length property.
     */
    public float getLength() {
        if (this.lengthProxy.get() == 0) {
            this.lengthProxy.set(length);
        }
        return this.lengthProxy.get();
    }

    /**
     * Sets the value of the length property.
     */
    public void setLength(float value) {
        this.length = value;
        this.lengthProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty lengthProperty() {
        return this.lengthProxy;
    }

    /**
     * Gets the value of the weight property.
     */
    public float getWeight() {
        if (this.weightProxy.get() == 0) {
            this.weightProxy.set(weight);
        }
        return this.weightProxy.get();
    }

    /**
     * Sets the value of the weight property.
     */
    public void setWeight(float value) {
        this.weight = value;
        this.weightProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public FloatProperty weightProperty() {
        return this.weightProxy;
    }

}
