//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 02:15:22 AM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Rank complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rank">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="short-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="full-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rank")
public class Rank {

    @XmlAttribute(name = "short-name")
    protected String shortName;
    @XmlAttribute(name = "full-name")
    protected String fullName;
    private final transient StringProperty shortNameProxy = new SimpleStringProperty();
    private final transient StringProperty fullNameProxy = new SimpleStringProperty();

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
        this.shortNameProxy.set(value);
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
        this.fullNameProxy.set(value);
    }

    /**
     * Gets the value of the shortName property.
     * 
     */
    public String getShortName() {
        if (this.shortNameProxy.get() == null) {
            this.shortNameProxy.set(shortName);
        }
        return this.shortNameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty shortNameProperty() {
        return this.shortNameProxy;
    }

    /**
     * Gets the value of the fullName property.
     * 
     */
    public String getFullName() {
        if (this.fullNameProxy.get() == null) {
            this.fullNameProxy.set(fullName);
        }
        return this.fullNameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty fullNameProperty() {
        return this.fullNameProxy;
    }

}
