//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 08:01:14 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;

import javax.xml.bind.annotation.XmlAttribute;


/**
 * <p>Java class for RGBColor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RGBColor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class RGBColor {

    protected Integer red;
    protected Integer green;
    protected Integer blue;
    private final transient IntegerProperty redProxy = new SimpleIntegerProperty();
    private final transient IntegerProperty greenProxy = new SimpleIntegerProperty();
    private final transient IntegerProperty blueProxy = new SimpleIntegerProperty();

    /**
     * Sets the value of the red property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @XmlAttribute(name = "red")
    public void setRed(Integer value) {
        this.red = value;
        this.redProxy.set(value);
    }

    /**
     * Sets the value of the green property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @XmlAttribute(name = "green")
    public void setGreen(Integer value) {
        this.green = value;
        this.greenProxy.set(value);
    }

    /**
     * Sets the value of the blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @XmlAttribute(name = "blue")
    public void setBlue(Integer value) {
        this.blue = value;
        this.blueProxy.set(value);
    }

    /**
     * Gets the value of the red property.
     * 
     */
    public Integer getRed() {
        return this.redProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty redProperty() {
        return this.redProxy;
    }

    /**
     * Gets the value of the green property.
     * 
     */
    public Integer getGreen() {
        return this.greenProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty greenProperty() {
        return this.greenProxy;
    }

    /**
     * Gets the value of the blue property.
     * 
     */
    public Integer getBlue() {
        return this.blueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty blueProperty() {
        return this.blueProxy;
    }

}
