//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 04:36:56 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.XmlAttribute;


/**
 * <p>Java class for RGBColor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RGBColor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class RGBColor {

    protected Short red;
    protected Short green;
    protected Short blue;
    private final transient ObjectProperty<Short> redProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Short> greenProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<Short> blueProxy = new SimpleObjectProperty<Short>();

    /**
     * Sets the value of the red property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    @XmlAttribute(name = "red")
    public void setRed(Short value) {
        this.red = value;
        this.redProxy.set(value);
    }

    /**
     * Sets the value of the green property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    @XmlAttribute(name = "green")
    public void setGreen(Short value) {
        this.green = value;
        this.greenProxy.set(value);
    }

    /**
     * Sets the value of the blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    @XmlAttribute(name = "blue")
    public void setBlue(Short value) {
        this.blue = value;
        this.blueProxy.set(value);
    }

    /**
     * Gets the value of the red property.
     * 
     */
    public Short getRed() {
        return this.redProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> redProperty() {
        return this.redProxy;
    }

    /**
     * Gets the value of the green property.
     * 
     */
    public Short getGreen() {
        return this.greenProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> greenProperty() {
        return this.greenProxy;
    }

    /**
     * Gets the value of the blue property.
     * 
     */
    public Short getBlue() {
        return this.blueProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> blueProperty() {
        return this.blueProxy;
    }

}
