//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 10:33:57 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ROF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ROF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="slow" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="normal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="rapid" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ROF")
public class ROF {

    @XmlAttribute(name = "slow")
    protected Float slow;
    @XmlAttribute(name = "normal")
    protected Float normal;
    @XmlAttribute(name = "rapid")
    protected Float rapid;
    private final transient FloatProperty slowProxy = new SimpleFloatProperty();
    private final transient FloatProperty normalProxy = new SimpleFloatProperty();
    private final transient FloatProperty rapidProxy = new SimpleFloatProperty();

    /**
     * Sets the value of the slow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSlow(Float value) {
        this.slow = value;
        this.slowProxy.set(value);
    }

    /**
     * Sets the value of the normal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNormal(Float value) {
        this.normal = value;
        this.normalProxy.set(value);
    }

    /**
     * Sets the value of the rapid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRapid(Float value) {
        this.rapid = value;
        this.rapidProxy.set(value);
    }

    /**
     * Gets the value of the slow property.
     * 
     */
    public Float getSlow() {
        this.slowProxy.set(slow);
        return this.slowProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty slowProperty() {
        return this.slowProxy;
    }

    /**
     * Gets the value of the normal property.
     * 
     */
    public Float getNormal() {
        this.normalProxy.set(normal);
        return this.normalProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty normalProperty() {
        return this.normalProxy;
    }

    /**
     * Gets the value of the rapid property.
     * 
     */
    public Float getRapid() {
        this.rapidProxy.set(rapid);
        return this.rapidProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rapidProperty() {
        return this.rapidProxy;
    }

}
