//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 08:01:14 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.*;
import javafx.collections.FXCollections;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Service">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="large-insignia" type="{}Insignia"/>
 *         &lt;element name="small-insignia" type="{}Insignia"/>
 *         &lt;element name="rank-list" type="{}RankList"/>
 *         &lt;element name="default-icon-colors" type="{}DefaultIconColors"/>
 *         &lt;element name="force" type="{}Force" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Service {

    protected String name;
    protected String description;
    protected Insignia largeInsignia;
    protected Insignia smallInsignia;
    protected RankList rankList;
    protected DefaultIconColors defaultIconColors;
    protected List<Force> force;
    protected int id;
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient StringProperty descriptionProxy = new SimpleStringProperty();
    private final transient ObjectProperty<Insignia> largeInsigniaProxy = new SimpleObjectProperty<Insignia>();
    private final transient ObjectProperty<Insignia> smallInsigniaProxy = new SimpleObjectProperty<Insignia>();
    private final transient ObjectProperty<RankList> rankListProxy = new SimpleObjectProperty<RankList>();
    private final transient ObjectProperty<DefaultIconColors> defaultIconColorsProxy = new SimpleObjectProperty<DefaultIconColors>();
    private final transient IntegerProperty idProxy = new SimpleIntegerProperty();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @XmlElement(required = true)
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @XmlElement(required = true)
    public void setDescription(String value) {
        this.description = value;
        this.descriptionProxy.set(value);
    }

    /**
     * Sets the value of the largeInsignia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Insignia }
     *
     */
    @XmlElement(required = true, name = "large-insignia")
    public void setLargeInsignia(Insignia value) {
        this.largeInsignia = value;
        this.largeInsigniaProxy.set(value);
    }

    /**
     * Sets the value of the smallInsignia property.
     *
     * @param value
     *     allowed object is
     *     {@link Insignia }
     *
     */
    @XmlElement(required = true, name = "small-insignia")
    public void setSmallInsignia(Insignia value) {
        this.smallInsignia = value;
        this.smallInsigniaProxy.set(value);
    }

    /**
     * Sets the value of the rankList property.
     *
     * @param value
     *     allowed object is
     *     {@link RankList }
     *
     */
    @XmlElement(required = true, name = "rank-list")
    public void setRankList(RankList value) {
        this.rankList = value;
        this.rankListProxy.set(value);
    }

    /**
     * Sets the value of the defaultIconColors property.
     *
     * @param value
     *     allowed object is
     *     {@link DefaultIconColors }
     *
     */
    @XmlElement(required = true, name = "default-icon-colors")
    public void setDefaultIconColors(DefaultIconColors value) {
        this.defaultIconColors = value;
        this.defaultIconColorsProxy.set(value);
    }

    /**
     * Sets the value of the id property.
     *
     */
    @XmlAttribute(required = true, name = "id")
    public void setId(int value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Gets the value of the name property.
     *
     */
    public String getName() {
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the description property.
     *
     */
    public String getDescription() {
        return this.descriptionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public StringProperty descriptionProperty() {
        return this.descriptionProxy;
    }

    /**
     * Gets the value of the largeInsignia property.
     *
     */
    public Insignia getLargeInsignia() {
        return this.largeInsigniaProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public ObjectProperty<Insignia> largeInsigniaProperty() {
        return this.largeInsigniaProxy;
    }

    /**
     * Gets the value of the smallInsignia property.
     *
     */
    public Insignia getSmallInsignia() {
        return this.smallInsigniaProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public ObjectProperty<Insignia> smallInsigniaProperty() {
        return this.smallInsigniaProxy;
    }

    /**
     * Gets the value of the rankList property.
     *
     */
    public RankList getRankList() {
        return this.rankListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public ObjectProperty<RankList> rankListProperty() {
        return this.rankListProxy;
    }

    /**
     * Gets the value of the defaultIconColors property.
     *
     */
    public DefaultIconColors getDefaultIconColors() {
        return this.defaultIconColorsProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     *
     */
    public ObjectProperty<DefaultIconColors> defaultIconColorsProperty() {
        return this.defaultIconColorsProxy;
    }

    /**
     * Gets the value of the force property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the force property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForce().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Force }
     * 
     * 
     */
    public List<Force> getForce() {
        if (force == null) {
            List backingList = new ArrayList<Force>();
            force = new SimpleListProperty<Force>(FXCollections.observableArrayList(backingList));
        }
        SimpleListProperty<Force> forceWrapper = ((SimpleListProperty<Force> ) this.force);
        return forceWrapper.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ListProperty<Force> forceProperty() {
        return ((ListProperty<Force> ) this.force);
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return this.idProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public IntegerProperty idProperty() {
        return this.idProxy;
    }

}
