//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.26 at 04:36:56 PM CET 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;


/**
 * <p>Java class for TargetPercentages complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetPercentages">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="front" type="{}Proportion"/>
 *         &lt;element name="left" type="{}Proportion"/>
 *         &lt;element name="right" type="{}Proportion"/>
 *         &lt;element name="rear" type="{}Proportion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class TargetPercentages {

    protected float front;
    protected float left;
    protected float right;
    protected float rear;
    private final transient FloatProperty frontProxy = new SimpleFloatProperty();
    private final transient FloatProperty leftProxy = new SimpleFloatProperty();
    private final transient FloatProperty rightProxy = new SimpleFloatProperty();
    private final transient FloatProperty rearProxy = new SimpleFloatProperty();

    /**
     * Sets the value of the front property.
     * 
     */
    public void setFront(float value) {
        this.front = value;
        this.frontProxy.set(value);
    }

    /**
     * Sets the value of the left property.
     * 
     */
    public void setLeft(float value) {
        this.left = value;
        this.leftProxy.set(value);
    }

    /**
     * Sets the value of the right property.
     * 
     */
    public void setRight(float value) {
        this.right = value;
        this.rightProxy.set(value);
    }

    /**
     * Sets the value of the rear property.
     * 
     */
    public void setRear(float value) {
        this.rear = value;
        this.rearProxy.set(value);
    }

    /**
     * Gets the value of the front property.
     * 
     */
    public float getFront() {
        return this.frontProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty frontProperty() {
        return this.frontProxy;
    }

    /**
     * Gets the value of the left property.
     * 
     */
    public float getLeft() {
        return this.leftProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty leftProperty() {
        return this.leftProxy;
    }

    /**
     * Gets the value of the right property.
     * 
     */
    public float getRight() {
        return this.rightProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rightProperty() {
        return this.rightProxy;
    }

    /**
     * Gets the value of the rear property.
     * 
     */
    public float getRear() {
        return this.rearProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty rearProperty() {
        return this.rearProxy;
    }

}
