//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 04:24:04 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleSpeeds complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="VehicleSpeeds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="road" type="{}SpeedData"/>
 *         &lt;element name="cross-country" type="{}SpeedData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleSpeeds", propOrder = {
        "road",
        "crossCountry"
})
public class VehicleSpeeds {

    private final transient ObjectProperty<SpeedData> roadProxy = new SimpleObjectProperty<SpeedData>();
    private final transient ObjectProperty<SpeedData> crossCountryProxy = new SimpleObjectProperty<SpeedData>();
    @XmlElement(required = true)
    protected SpeedData road;
    @XmlElement(name = "cross-country", required = true)
    protected SpeedData crossCountry;

    /**
     * Gets the value of the road property.
     */
    public SpeedData getRoad() {
        if (this.roadProxy.get() == null) {
            this.roadProxy.set(road);
        }
        return this.roadProxy.get();
    }

    /**
     * Sets the value of the road property.
     *
     * @param value allowed object is
     *              {@link SpeedData }
     */
    public void setRoad(SpeedData value) {
        this.road = value;
        this.roadProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<SpeedData> roadProperty() {
        return this.roadProxy;
    }

    /**
     * Gets the value of the crossCountry property.
     */
    public SpeedData getCrossCountry() {
        if (this.crossCountryProxy.get() == null) {
            this.crossCountryProxy.set(crossCountry);
        }
        return this.crossCountryProxy.get();
    }

    /**
     * Sets the value of the crossCountry property.
     *
     * @param value allowed object is
     *              {@link SpeedData }
     */
    public void setCrossCountry(SpeedData value) {
        this.crossCountry = value;
        this.crossCountryProxy.set(value);
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     */
    public ObjectProperty<SpeedData> crossCountryProperty() {
        return this.crossCountryProxy;
    }

}
