//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 10:33:57 PM CEST 
//


package net.deludobellico.stabeditor.data.jaxb;

import javafx.beans.property.FloatProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Weapon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Weapon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="picture" type="{}Picture"/>
 *         &lt;element name="picture-filename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{}WeaponSize"/>
 *         &lt;element name="crew" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="reliability" type="{}Proportion"/>
 *         &lt;element name="armaments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{}WeaponType"/>
 *         &lt;element name="single-shot" type="{}YesNo"/>
 *         &lt;element name="primary-role" type="{}PrimaryRole"/>
 *         &lt;element name="calibre" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="muzzle-velocity" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="must-deploy-to-fire" type="{}YesNo"/>
 *         &lt;element name="performance-list" type="{}PerformanceList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Weapon", propOrder = {
    "name",
    "description",
    "picture",
    "pictureFilename",
    "size",
    "crew",
    "reliability",
    "armaments",
    "type",
    "singleShot",
    "primaryRole",
    "calibre",
    "muzzleVelocity",
    "mustDeployToFire",
    "performanceList"
})
public class Weapon {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Picture picture;
    @XmlElement(name = "picture-filename", required = true)
    protected String pictureFilename;
    @XmlElement(required = true)
    protected WeaponSize size;
    protected byte crew;
    protected float reliability;
    @XmlElement(required = true)
    protected String armaments;
    @XmlElement(required = true)
    protected WeaponType type;
    @XmlElement(name = "single-shot", required = true)
    protected YesNo singleShot;
    @XmlElement(name = "primary-role", required = true)
    protected PrimaryRole primaryRole;
    protected float calibre;
    @XmlElement(name = "muzzle-velocity")
    protected short muzzleVelocity;
    @XmlElement(name = "must-deploy-to-fire", required = true)
    protected YesNo mustDeployToFire;
    @XmlElement(name = "performance-list", required = true)
    protected PerformanceList performanceList;
    @XmlAttribute(name = "id")
    protected Short id;
    private final transient StringProperty nameProxy = new SimpleStringProperty();
    private final transient StringProperty descriptionProxy = new SimpleStringProperty();
    private final transient ObjectProperty<Picture> pictureProxy = new SimpleObjectProperty<Picture>();
    private final transient StringProperty pictureFilenameProxy = new SimpleStringProperty();
    private final transient ObjectProperty<WeaponSize> sizeProxy = new SimpleObjectProperty<WeaponSize>();
    private final transient ObjectProperty<Byte> crewProxy = new SimpleObjectProperty<Byte>();
    private final transient FloatProperty reliabilityProxy = new SimpleFloatProperty();
    private final transient StringProperty armamentsProxy = new SimpleStringProperty();
    private final transient ObjectProperty<WeaponType> typeProxy = new SimpleObjectProperty<WeaponType>();
    private final transient ObjectProperty<YesNo> singleShotProxy = new SimpleObjectProperty<YesNo>();
    private final transient ObjectProperty<PrimaryRole> primaryRoleProxy = new SimpleObjectProperty<PrimaryRole>();
    private final transient FloatProperty calibreProxy = new SimpleFloatProperty();
    private final transient ObjectProperty<Short> muzzleVelocityProxy = new SimpleObjectProperty<Short>();
    private final transient ObjectProperty<YesNo> mustDeployToFireProxy = new SimpleObjectProperty<YesNo>();
    private final transient ObjectProperty<PerformanceList> performanceListProxy = new SimpleObjectProperty<PerformanceList>();
    private final transient ObjectProperty<Short> idProxy = new SimpleObjectProperty<Short>();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
        this.nameProxy.set(value);
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
        this.descriptionProxy.set(value);
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.Picture }
     *     
     */
    public void setPicture(Picture value) {
        this.picture = value;
        this.pictureProxy.set(value);
    }

    /**
     * Sets the value of the pictureFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureFilename(String value) {
        this.pictureFilename = value;
        this.pictureFilenameProxy.set(value);
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.WeaponSize }
     *     
     */
    public void setSize(WeaponSize value) {
        this.size = value;
        this.sizeProxy.set(value);
    }

    /**
     * Sets the value of the crew property.
     * 
     */
    public void setCrew(byte value) {
        this.crew = value;
        this.crewProxy.set(value);
    }

    /**
     * Sets the value of the reliability property.
     * 
     */
    public void setReliability(float value) {
        this.reliability = value;
        this.reliabilityProxy.set(value);
    }

    /**
     * Sets the value of the armaments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArmaments(String value) {
        this.armaments = value;
        this.armamentsProxy.set(value);
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.WeaponType }
     *     
     */
    public void setType(WeaponType value) {
        this.type = value;
        this.typeProxy.set(value);
    }

    /**
     * Sets the value of the singleShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.YesNo }
     *     
     */
    public void setSingleShot(YesNo value) {
        this.singleShot = value;
        this.singleShotProxy.set(value);
    }

    /**
     * Sets the value of the primaryRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.PrimaryRole }
     *     
     */
    public void setPrimaryRole(PrimaryRole value) {
        this.primaryRole = value;
        this.primaryRoleProxy.set(value);
    }

    /**
     * Sets the value of the calibre property.
     * 
     */
    public void setCalibre(float value) {
        this.calibre = value;
        this.calibreProxy.set(value);
    }

    /**
     * Sets the value of the muzzleVelocity property.
     * 
     */
    public void setMuzzleVelocity(short value) {
        this.muzzleVelocity = value;
        this.muzzleVelocityProxy.set(value);
    }

    /**
     * Sets the value of the mustDeployToFire property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.YesNo }
     *     
     */
    public void setMustDeployToFire(YesNo value) {
        this.mustDeployToFire = value;
        this.mustDeployToFireProxy.set(value);
    }

    /**
     * Sets the value of the performanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link net.deludobellico.stabeditor.data.jaxb.PerformanceList }
     *     
     */
    public void setPerformanceList(PerformanceList value) {
        this.performanceList = value;
        this.performanceListProxy.set(value);
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
        this.idProxy.set(value);
    }

    /**
     * Gets the value of the name property.
     * 
     */
    public String getName() {
        this.nameProxy.set(name);
        return this.nameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty nameProperty() {
        return this.nameProxy;
    }

    /**
     * Gets the value of the description property.
     * 
     */
    public String getDescription() {
        this.descriptionProxy.set(description);
        return this.descriptionProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty descriptionProperty() {
        return this.descriptionProxy;
    }

    /**
     * Gets the value of the picture property.
     * 
     */
    public Picture getPicture() {
        this.pictureProxy.set(picture);
        return this.pictureProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Picture> pictureProperty() {
        return this.pictureProxy;
    }

    /**
     * Gets the value of the pictureFilename property.
     * 
     */
    public String getPictureFilename() {
        this.pictureFilenameProxy.set(pictureFilename);
        return this.pictureFilenameProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty pictureFilenameProperty() {
        return this.pictureFilenameProxy;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public WeaponSize getSize() {
        this.sizeProxy.set(size);
        return this.sizeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<WeaponSize> sizeProperty() {
        return this.sizeProxy;
    }

    /**
     * Gets the value of the crew property.
     * 
     */
    public byte getCrew() {
        this.crewProxy.set(crew);
        return this.crewProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Byte> crewProperty() {
        return this.crewProxy;
    }

    /**
     * Gets the value of the reliability property.
     * 
     */
    public float getReliability() {
        this.reliabilityProxy.set(reliability);
        return this.reliabilityProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty reliabilityProperty() {
        return this.reliabilityProxy;
    }

    /**
     * Gets the value of the armaments property.
     * 
     */
    public String getArmaments() {
        this.armamentsProxy.set(armaments);
        return this.armamentsProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public StringProperty armamentsProperty() {
        return this.armamentsProxy;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public WeaponType getType() {
        this.typeProxy.set(type);
        return this.typeProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<WeaponType> typeProperty() {
        return this.typeProxy;
    }

    /**
     * Gets the value of the singleShot property.
     * 
     */
    public YesNo getSingleShot() {
        this.singleShotProxy.set(singleShot);
        return this.singleShotProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<YesNo> singleShotProperty() {
        return this.singleShotProxy;
    }

    /**
     * Gets the value of the primaryRole property.
     * 
     */
    public PrimaryRole getPrimaryRole() {
        this.primaryRoleProxy.set(primaryRole);
        return this.primaryRoleProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<PrimaryRole> primaryRoleProperty() {
        return this.primaryRoleProxy;
    }

    /**
     * Gets the value of the calibre property.
     * 
     */
    public float getCalibre() {
        this.calibreProxy.set(calibre);
        return this.calibreProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public FloatProperty calibreProperty() {
        return this.calibreProxy;
    }

    /**
     * Gets the value of the muzzleVelocity property.
     * 
     */
    public short getMuzzleVelocity() {
        this.muzzleVelocityProxy.set(muzzleVelocity);
        return this.muzzleVelocityProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> muzzleVelocityProperty() {
        return this.muzzleVelocityProxy;
    }

    /**
     * Gets the value of the mustDeployToFire property.
     * 
     */
    public YesNo getMustDeployToFire() {
        this.mustDeployToFireProxy.set(mustDeployToFire);
        return this.mustDeployToFireProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<YesNo> mustDeployToFireProperty() {
        return this.mustDeployToFireProxy;
    }

    /**
     * Gets the value of the performanceList property.
     * 
     */
    public PerformanceList getPerformanceList() {
        this.performanceListProxy.set(performanceList);
        return this.performanceListProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<PerformanceList> performanceListProperty() {
        return this.performanceListProxy;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public Short getId() {
        this.idProxy.set(id);
        return this.idProxy.get();
    }

    /**
     * Generated by FXBeanPropertyXJCPlugin.
     * 
     */
    public ObjectProperty<Short> idProperty() {
        return this.idProxy;
    }

}
